using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using HarmonyLib;
using UnityEngine;

namespace IMDataCore
{
    /// <summary>
    /// Captures single-creation lifecycle events.
    /// </summary>
    [HarmonyPatch(typeof(singles), nameof(singles.AddNewSingle))]
    internal static class singles_AddNewSingle_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Records one single-created event after production row is added.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(singles._single single)
        {
            IMDataCoreController.Instance.CaptureSingleCreated(single);
        }
    }

    /// <summary>
    /// Captures final single-release state after all modded postfix changes complete.
    /// </summary>
    [HarmonyPatch(typeof(singles), nameof(singles.ReleaseSingle))]
    internal static class singles_ReleaseSingle_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Records single participation events and projections.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(singles._single single)
        {
            IMDataCoreController.Instance.CaptureSingleReleased(single);
        }
    }

    /// <summary>
    /// Captures chart-position resolution when chart popup renders ranked rows.
    /// </summary>
    [HarmonyPatch(typeof(Chart_Song), nameof(Chart_Song.Set))]
    internal static class Chart_Song_Set_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Records chart-position backfill for one player single.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(Rivals._group._single Single, int Number)
        {
            if (Single == null || !Single.Player || Number <= CoreConstants.ZeroBasedListStartIndex)
            {
                return;
            }

            singles._single playerSingle = Single.GetSingle();
            if (playerSingle == null)
            {
                return;
            }

            IMDataCoreController.Instance.CaptureSingleChartPositionResolved(
                playerSingle,
                Number,
                CoreConstants.EventSourceSingleChartPopupPatch);
        }
    }

    /// <summary>
    /// Tags idol earnings generated by single-release payout flow.
    /// </summary>
    [HarmonyPatch(typeof(singles), CoreConstants.HarmonySinglesAddMoneyMethodName, new Type[] { typeof(singles._single) })]
    internal static class singles_AddMoney_IMDataCoreEarningsSource_Patch
    {
        [HarmonyPrefix]
        [HarmonyPriority(Priority.Last)]
        private static void Prefix()
        {
            ActivityEarningsSourceContext.Set(CoreConstants.EarningsSourceSingleRelease);
        }

        [HarmonyPostfix]
        [HarmonyPriority(Priority.Last)]
        private static void Postfix()
        {
            ActivityEarningsSourceContext.Clear();
        }

        [HarmonyFinalizer]
        [HarmonyPriority(Priority.Last)]
        private static Exception Finalizer(Exception __exception)
        {
            ActivityEarningsSourceContext.Clear();
            return __exception;
        }
    }

    /// <summary>
    /// Captures single-cancellation lifecycle events.
    /// </summary>
    [HarmonyPatch(typeof(singles), nameof(singles.CancelSingle))]
    internal static class singles_CancelSingle_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Records one single-cancel event after cancellation logic completes.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(singles._single __0)
        {
            IMDataCoreController.Instance.CaptureSingleCancelled(__0);
        }
    }

    /// <summary>
    /// Captures single status transitions.
    /// </summary>
    [HarmonyPatch(typeof(singles._single), nameof(singles._single.SetStatus))]
    internal static class singles_single_SetStatus_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Captures previous single status before mutation.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Prefix(singles._single __instance, out singles._single._status __state)
        {
            __state = __instance != null ? __instance.status : singles._single._status.normal;
        }

        /// <summary>
        /// Records single status-change event after mutation.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(singles._single __instance, singles._single._status __state)
        {
            singles._single._status finalStatus = __instance != null ? __instance.status : __state;
            IMDataCoreController.Instance.CaptureSingleStatusTransition(__instance, __state, finalStatus);
        }
    }

    /// <summary>
    /// Captures single cast-change events when one idol is removed from single cast.
    /// </summary>
    [HarmonyPatch(typeof(singles._single), nameof(singles._single.RemoveGirl))]
    internal static class singles_single_RemoveGirl_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Captures single cast snapshot before removal mutation.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Prefix(singles._single __instance, out SingleCastChangeSnapshot __state)
        {
            __state = IMDataCoreController.Instance.CreateSingleCastChangeSnapshot(__instance);
        }

        /// <summary>
        /// Records cast-change event after removal logic completes.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(singles._single __instance, data_girls.girls __0, SingleCastChangeSnapshot __state)
        {
            IMDataCoreController.Instance.CaptureSingleCastChanged(__instance, __0, __state);
        }
    }

    /// <summary>
    /// Captures single cast changes committed from the single senbatsu popup.
    /// </summary>
    [HarmonyPatch(typeof(SinglePopup_Senbatsu), nameof(SinglePopup_Senbatsu.OnConfirm))]
    internal static class SinglePopup_Senbatsu_OnConfirm_IMDataCoreCapture_Patch
    {
        /// <summary>
        /// Captures pre-commit single cast state for existing single edits.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Prefix(SinglePopup_Senbatsu __instance, out SingleCastChangeSnapshot __state)
        {
            if (__instance == null || __instance.is_new || __instance.single == null)
            {
                __state = null;
                return;
            }

            __state = IMDataCoreController.Instance.CreateSingleCastChangeSnapshot(__instance.single);
        }

        /// <summary>
        /// Records one single cast-change event after popup commit applies.
        /// </summary>
        [HarmonyPriority(Priority.Last)]
        private static void Postfix(SinglePopup_Senbatsu __instance, SingleCastChangeSnapshot __state)
        {
            if (__instance == null || __instance.is_new || __state == null)
            {
                return;
            }

            IMDataCoreController.Instance.CaptureSingleCastChangedFromPopup(__instance.single, __state);
            IMDataCoreController.Instance.CaptureSingleGroupChangedFromPopup(__instance.single, __state);
        }
    }

}
