namespace IMDataCore.DataMigrationTool.Gui;

internal enum HelpTopic
{
    Overview,
    BeforeYouStart,
    IndividualMigration,
    ReverseMatching,
    Validation,
    BranchRepair,
    BulkScan,
    BulkConvert,
    MatchResolver,
    FutureTail,
    Cleanup,
    Statuses,
    Logs,
}

internal sealed record HelpSection(HelpTopic Topic, string Title, string Body);

internal static class HelpContent
{
    public static IReadOnlyList<HelpSection> Current() => ForLanguage(Localization.CurrentCode);

    public static IReadOnlyList<HelpSection> ForLanguage(string code)
    {
        return code switch
        {
            "pt-BR" => pt_BR(),
            "ru" => ru(),
            "fr" => fr(),
            "ja" => ja(),
            "ko" => ko(),
            "zh-Hans" => zh_Hans(),
            _ => en()
        };
    }

    private static IReadOnlyList<HelpSection> en() => new HelpSection[]
    {
        new(HelpTopic.Overview, "What the IMDataCore Data Migration Tool is for", "The IMDataCore Data Migration Tool moves legacy IMDataCore 1.0.0–1.3.0 data to the current IMDataCore sidecar format v6, which uses journal format v3. It needs the old IMDataCore data and, in most cases, the matching normal Idol Manager save.\n\nNothing is changed just by opening a file, inspecting it, scanning it, or using Validate only. Writing happens only when you choose a migration or repair action."),
        new(HelpTopic.BeforeYouStart, "Before you start", "1. Close Idol Manager before writing migrated data.\n2. Keep a backup of old saves and old IMDataCore folders until you have checked the new result.\n3. Use the normal Idol Manager save that belongs to the old IMDataCore data whenever possible.\n4. If the Data Migration Tool is unsure about a match, review it instead of guessing.\n5. Cleanup is optional. The Data Migration Tool can send old data to the Windows Recycle Bin after a successful migration."),
        new(HelpTopic.IndividualMigration, "Individual migration", "Use this when you want to move one old save at a time.\n\n1. Pick the raw vanilla game save. This is the normal Idol Manager save.json or auto_save.json.\n2. The Data Migration Tool will show likely old IMDataCore data. Choose a suggested match or browse to the old im_data_core.db yourself.\n3. Use Inspect if you want to see what the Data Migration Tool found inside the old data.\n4. Leave the destination at the normal IMDataCore folder unless you are intentionally testing somewhere else.\n5. Choose Validate only first. This checks the planned conversion without writing the new IMDataCore output file.\n6. If the result looks right, choose Migrate copy.\n7. Open destination if you want to look at the new file. If cleanup is enabled, the old source is recycled only after the new output has been written and checked again."),
        new(HelpTopic.ReverseMatching, "Starting from an old IMDataCore file", "Use this when you found an old database but are not sure which normal save belongs to it.\n\n1. Browse to the old IMDataCore file first.\n2. Choose Inspect.\n3. Scan the Idol Manager data folder for vanilla saves.\n4. The Data Migration Tool lists the saves that look most likely to belong to that database.\n5. Review the save name, player, group, date, and path.\n6. Choose Use vanilla save when you find the right one.\n7. Validate before migrating."),
        new(HelpTopic.Validation, "Validate only", "Validate only is the safe preview button. It builds the planned current-format data in memory and checks it, but does not write the migrated IMDataCore file.\n\nSUCCESS means the planned output is structurally valid. For very old IMDataCore versions, the Data Migration Tool may still warn that it cannot prove the old database came from that exact save because those versions did not keep an exact record linking the database to that exact save moment. That warning is about certainty of the match, not about whether the new file can be built.\n\nOld IMDataCore could keep saving while the vanilla save file was not overwritten. Because of that, a database being newer than the vanilla save does not automatically mean the data is bad."),
        new(HelpTopic.BranchRepair, "Repair branch contamination", "Use this when the Data Migration Tool finds that one old database contains more than one play timeline, usually shown by the in-game date jumping backwards.\n\n1. Open Repair branch contamination.\n2. Read the branch list and the summary.\n3. Conservative branch salvage keeps only the branch that best matches the selected vanilla save and only up to that save's date.\n4. Clean baseline keeps the vanilla save binding but throws away the old event history and old custom state. Use it when no branch can be chosen confidently.\n5. Validate the repair first.\n6. Write the repair only after you are satisfied with the selected branch or baseline choice.\n\nThe Data Migration Tool never invents missing events."),
        new(HelpTopic.BulkScan, "Bulk contamination scan", "This scan is for checking a whole folder of old IMDataCore saves before converting them. It does not modify the old files.\n\n1. Choose the old IMDataCore saves root.\n2. Choose Scan.\n3. Wait for the table to finish filling.\n4. No branch reset detected means the scan did not see the in-game date jump backwards. It is not a promise that the data is perfect.\n5. Contaminated / divergent timeline means one or more backwards jumps were found.\n6. Select a row to read the details.\n7. Export CSV or JSON if you want a report, or open Bulk convert to plan the migrations."),
        new(HelpTopic.BulkConvert, "Bulk convert", "Bulk convert plans many migrations together. It is deliberately cautious and will hold uncertain rows for you to review.\n\n1. Choose the legacy root, the Idol Manager data root, and the destination IMDataCore root.\n2. Choose how contaminated saves should be handled. Auto-repair is the usual choice: salvage a branch when the evidence is good, otherwise use a clean baseline.\n3. Choose Build plan. Nothing is written yet.\n4. Review the Status and Details columns.\n5. Resolve weak, ambiguous, or missing matches with Resolve match when needed.\n6. Review future-tail truncation rows. These are saves where IMDataCore continued recording after the vanilla save's date without a detected branch reset.\n7. Choose Validate selected for a no-write test.\n8. Choose Convert selected when the plan looks right.\n9. Export the result if you want a record of what happened."),
        new(HelpTopic.MatchResolver, "Resolve match", "The match resolver lets you make the final choice when the old data does not identify one vanilla save clearly enough.\n\nMatch scores are hints, not a verdict. A file-specific match is normally stronger than an old agency-wide match, but you should still use the save details you recognize.\n\n1. Select the legacy row in Bulk convert.\n2. Choose Resolve match.\n3. Compare the candidate save paths, player name, group name, dates, and other identity details.\n4. Select the correct save and confirm it.\n5. If the correct vanilla save is not listed, use Browse save to point the Data Migration Tool to it directly.\n\nIf two old databases would then target the same output, the Data Migration Tool asks before replacing the existing plan choice."),
        new(HelpTopic.FutureTail, "Future-tail truncation", "Older IMDataCore could record data after the last time you saved that vanilla slot. For example, you might play for a while and then exit without overwriting that manual save.\n\nWhen the event dates move forward normally and simply continue past the vanilla save date, the Data Migration Tool can offer future-tail truncation. It keeps events only through the vanilla save's date and removes the later tail. Old mod-specific saved values are not kept because the Data Migration Tool cannot safely rewind those values to the earlier moment.\n\nThis is different from branch contamination, where the timeline actually jumps backwards."),
        new(HelpTopic.Cleanup, "Cleaning up old IMDataCore data", "Cleanup is optional. It is safer to migrate first, check the result, and clean up afterward.\n\n• Recycle after success only becomes eligible after the new IMDataCore output was written, reopened, and checked again.\n• Recycle successfully migrated removes sources that completed successfully.\n• Recycle orphaned sources applies only to true No vanilla match rows. Weak and ambiguous matches are not treated as orphans.\n• Files go to the Windows Recycle Bin instead of being permanently deleted.\n• If the old per-save folder becomes empty after its IMDataCore files are recycled, the Data Migration Tool recycles that empty folder too.\n• A database containing data for several saves is kept until every save that depends on it is safe to remove."),
        new(HelpTopic.Statuses, "Common bulk-plan statuses", "Ready: normal migration — the old data and vanilla save have a usable match and the plan passed validation.\n\nReady: branch salvage — the Data Migration Tool found multiple timelines and has a branch it can keep with enough confidence.\n\nReady: clean baseline fallback — the vanilla save is known, but the old mixed history cannot be separated safely.\n\nReady: future-tail truncation — the timeline is continuous but extends beyond the selected vanilla save date.\n\nWeak vanilla match — the Data Migration Tool found a possible save, but the automatic evidence is not strong enough. Use Resolve match.\n\nAmbiguous vanilla match — two or more saves look equally good. Use Resolve match.\n\nNo vanilla match — no recognized current vanilla save matched. The old save may have been deleted or moved somewhere else.\n\nSuperseded legacy source — a stronger old source already targets the same vanilla save, so the Data Migration Tool avoids writing twice.\n\nValidation failed — read the Details box. The row needs attention before it can be written."),
        new(HelpTopic.Logs, "Logs and troubleshooting", "Most users do not need the diagnostic logs. Use Logs when a window fails, a scan throws an error, or you need to report exactly what happened.\n\nOpen destination opens the current IMDataCore output folder. It is useful after a migration when you want to confirm that the new IMDataCore output file exists.\n\nIf a warning is unclear, keep the old files, do not force cleanup, and review the row or individual migration before continuing."),
    };

    private static IReadOnlyList<HelpSection> pt_BR() => new HelpSection[]
    {
        new(HelpTopic.Overview, "Para que serve a Ferramenta de Migração de Dados do IMDataCore", "A Ferramenta de Migração de Dados do IMDataCore move dados antigos do IMDataCore 1.0.0–1.3.0 para o formato atual de dados versão 6, com registro de alterações versão 3. Na maioria dos casos, ela precisa dos dados antigos do IMDataCore e do save normal correspondente do Idol Manager.\n\nNada é alterado apenas ao abrir, inspecionar ou escanear um arquivo, nem ao usar Somente validar. A gravação só acontece quando você escolhe uma ação de migração ou reparo."),
        new(HelpTopic.BeforeYouStart, "Antes de começar", "1. Feche o Idol Manager antes de gravar dados migrados.\n2. Mantenha uma cópia dos saves antigos e das pastas antigas do IMDataCore até conferir o resultado novo.\n3. Sempre que possível, use o save normal do Idol Manager que pertence aos dados antigos do IMDataCore.\n4. Se a Ferramenta de Migração de Dados não tiver certeza de uma correspondência, revise em vez de adivinhar.\n5. A limpeza é opcional. A Ferramenta de Migração de Dados pode enviar os dados antigos para a Lixeira do Windows depois de uma migração bem-sucedida."),
        new(HelpTopic.IndividualMigration, "Migração individual", "Use isto para migrar um save antigo por vez.\n\n1. Escolha o save original do jogo. É o save.json ou auto_save.json normal do Idol Manager.\n2. A Ferramenta de Migração de Dados mostrará dados antigos prováveis do IMDataCore. Escolha uma sugestão ou procure o im_data_core.db antigo manualmente.\n3. Use Inspecionar se quiser ver o que foi encontrado nos dados antigos.\n4. Deixe o destino na pasta normal IMDataCore, a menos que esteja testando de propósito em outro lugar.\n5. Escolha Somente validar primeiro. Isso verifica a conversão planejada sem gravar o novo sidecar.\n6. Se o resultado estiver correto, escolha Migrar cópia.\n7. Abra o destino se quiser ver o novo arquivo. Se a limpeza estiver ativada, a origem antiga só vai para a Lixeira depois que a nova saída for gravada e verificada novamente."),
        new(HelpTopic.ReverseMatching, "Começando por um arquivo antigo do IMDataCore", "Use isto quando você encontrou um banco de dados antigo mas não sabe qual save normal pertence a ele.\n\n1. Primeiro escolha o arquivo antigo do IMDataCore.\n2. Escolha Inspecionar.\n3. Escaneie a pasta data do Idol Manager em busca de saves originais.\n4. A Ferramenta de Migração de Dados lista os saves que parecem mais prováveis para aquele banco.\n5. Confira nome do save, jogador, grupo, data e caminho.\n6. Escolha Usar save original quando encontrar o correto.\n7. Valide antes de migrar."),
        new(HelpTopic.Validation, "Somente validar", "Somente validar é a prévia segura. Ele monta em memória os dados no formato atual e os verifica, mas não grava o sidecar migrado.\n\nSUCESSO significa que a saída planejada é estruturalmente válida. Em versões muito antigas do IMDataCore, a Ferramenta de Migração de Dados ainda pode avisar que não consegue provar que aquele banco veio exatamente daquele save, porque essas versões não guardavam um checkpoint exato. Esse aviso é sobre a certeza da correspondência, não sobre o formato JSON.\n\nO IMDataCore antigo podia continuar salvando mesmo sem o arquivo de save original ser sobrescrito. Por isso, um banco ser mais novo que o save original não significa automaticamente que os dados estão ruins."),
        new(HelpTopic.BranchRepair, "Reparar contaminação entre ramificações", "Use isto quando a Ferramenta de Migração de Dados encontra mais de uma linha de jogo dentro de um banco antigo, normalmente indicada pela data do jogo voltando para trás.\n\n1. Abra Reparar contaminação entre ramificações.\n2. Leia a lista de ramificações e o resumo.\n3. O salvamento conservador mantém apenas a ramificação que melhor combina com o save original selecionado e somente até a data desse save.\n4. A linha de base limpa mantém a ligação com o save original, mas descarta o histórico antigo de eventos e o estado personalizado antigo. Use quando nenhuma ramificação puder ser escolhida com confiança.\n5. Valide o reparo primeiro.\n6. Grave o reparo somente depois de conferir a escolha.\n\nA Ferramenta de Migração de Dados nunca inventa eventos ausentes."),
        new(HelpTopic.BulkScan, "Escaneamento em massa de contaminação", "Este escaneamento verifica uma pasta inteira de saves antigos do IMDataCore antes da conversão. Ele não modifica os arquivos antigos.\n\n1. Escolha a raiz dos saves antigos do IMDataCore.\n2. Escolha Escanear.\n3. Espere a tabela terminar de preencher.\n4. Nenhum reinício de ramificação detectado significa apenas que a data do jogo não voltou para trás durante o escaneamento. Não é uma garantia de perfeição.\n5. Linha do tempo contaminada/divergente significa que foram encontrados um ou mais saltos para trás.\n6. Selecione uma linha para ler os detalhes.\n7. Exporte CSV ou JSON se quiser um relatório, ou abra Conversão em massa para planejar as migrações."),
        new(HelpTopic.BulkConvert, "Conversão em massa", "A conversão em massa planeja várias migrações juntas. Ela é cautelosa de propósito e deixa linhas incertas para você revisar.\n\n1. Escolha a raiz antiga, a raiz data do Idol Manager e a raiz IMDataCore de destino.\n2. Escolha como saves contaminados devem ser tratados. Reparo automático costuma ser a opção normal: preserva uma ramificação quando há boa evidência e, caso contrário, usa uma linha de base limpa.\n3. Escolha Criar plano. Nada é gravado ainda.\n4. Revise as colunas Status e Detalhes.\n5. Resolva correspondências fracas, ambíguas ou ausentes com Resolver correspondência.\n6. Revise linhas de corte de cauda futura.\n7. Escolha Validar selecionados para um teste sem gravação.\n8. Escolha Converter selecionados quando o plano estiver correto.\n9. Exporte o resultado se quiser um registro."),
        new(HelpTopic.MatchResolver, "Resolver correspondência", "O resolvedor permite que você faça a escolha final quando os dados antigos não identificam um único save original com clareza.\n\nAs pontuações são pistas, não uma decisão final. Uma correspondência específica de arquivo costuma ser mais forte que uma correspondência antiga por agência, mas use os detalhes do save que você reconhece.\n\n1. Selecione a linha antiga na Conversão em massa.\n2. Escolha Resolver correspondência.\n3. Compare caminhos, nome do jogador, grupo, datas e outros detalhes.\n4. Selecione o save correto e confirme.\n5. Se o save correto não estiver na lista, use Procurar save para apontar diretamente para ele.\n\nSe dois bancos antigos passarem a apontar para a mesma saída, a Ferramenta de Migração de Dados pergunta antes de trocar a escolha do plano."),
        new(HelpTopic.FutureTail, "Corte de cauda futura", "O IMDataCore antigo podia registrar dados depois da última vez que aquele slot original foi salvo. Por exemplo, você podia continuar jogando e sair sem sobrescrever o save manual.\n\nQuando as datas dos eventos avançam normalmente e apenas continuam além da data do save original, a Ferramenta de Migração de Dados pode oferecer corte de cauda futura. Ele mantém eventos somente até a data do save e remove os eventos posteriores. Dados personalizados mutáveis antigos não são mantidos porque não é possível voltar esses valores com segurança para o momento anterior.\n\nIsso é diferente de contaminação entre ramificações, em que a linha do tempo realmente volta para trás."),
        new(HelpTopic.Cleanup, "Limpeza de dados antigos do IMDataCore", "A limpeza é opcional. É mais seguro migrar, conferir o resultado e limpar depois.\n\n• Reciclar após sucesso só fica disponível depois que a nova saída v6 foi gravada, reaberta e validada novamente.\n• Reciclar migrados com sucesso remove origens concluídas com sucesso.\n• Reciclar origens órfãs vale apenas para linhas realmente Sem correspondência de save original. Correspondências fracas e ambíguas não são tratadas como órfãs.\n• Os arquivos vão para a Lixeira do Windows, não são apagados permanentemente.\n• Se a pasta antiga do save ficar vazia depois da reciclagem dos arquivos IMDataCore, a Ferramenta de Migração de Dados recicla essa pasta vazia também.\n• Um banco com vários fluxos de save é mantido até que todos possam ser removidos com segurança."),
        new(HelpTopic.Statuses, "Status comuns do plano em massa", "Pronto: migração normal — há uma correspondência utilizável e o plano passou na validação.\n\nPronto: salvamento de ramificação — há várias linhas do tempo e existe uma ramificação que pode ser mantida com confiança suficiente.\n\nPronto: linha de base limpa — o save original é conhecido, mas o histórico misturado não pode ser separado com segurança.\n\nPronto: corte de cauda futura — a linha do tempo é contínua, mas vai além da data do save selecionado.\n\nCorrespondência fraca — há um candidato, mas a evidência automática não é forte. Use Resolver correspondência.\n\nCorrespondência ambígua — dois ou mais saves parecem igualmente bons. Use Resolver correspondência.\n\nSem correspondência — nenhum save original reconhecido correspondeu. O save antigo pode ter sido apagado ou movido.\n\nOrigem antiga substituída — outra origem antiga mais forte já aponta para o mesmo save.\n\nFalha na validação — leia a caixa Detalhes antes de continuar."),
        new(HelpTopic.Logs, "Logs e solução de problemas", "A maioria das pessoas não precisa dos logs de diagnóstico. Use Logs quando uma janela falhar, um escaneamento der erro ou você precisar relatar exatamente o que aconteceu.\n\nAbrir destino abre a pasta atual de saída do IMDataCore. É útil depois de uma migração para confirmar que o novo sidecar existe.\n\nSe um aviso não estiver claro, mantenha os arquivos antigos, não force a limpeza e revise a linha ou a migração individual antes de continuar."),
    };

    private static IReadOnlyList<HelpSection> ru() => new HelpSection[]
    {
        new(HelpTopic.Overview, "Для чего нужен инструмент переноса данных", "Инструмент переносит старые данные Ай-Эм Дата Кор 1.0.0–1.3.0 в текущий формат данных версии 6, где используется формат журнала изменений версии 3. Нужны старые данные и, в большинстве случаев, соответствующее обычное сохранение Айдол Менеджер.\n\nПростое открытие, просмотр или сканирование файла ничего не меняет. Режим «Только проверить» тоже ничего не записывает. Запись начинается только после выбора миграции или ремонта."),
        new(HelpTopic.BeforeYouStart, "Перед началом", "1. Закройте Айдол Менеджер перед записью перенесённых данных.\n2. Храните копию старых сохранений и старых папок Ай-Эм Дата Кор, пока не проверите новый результат.\n3. По возможности используйте обычное сохранение Айдол Менеджер, которому принадлежат старые данные Ай-Эм Дата Кор.\n4. Если инструмент переноса данных не уверен в соответствии, проверьте его вручную вместо угадывания.\n5. Очистка необязательна. После успешной миграции инструмент переноса данных может отправить старые данные в Корзину Виндоус."),
        new(HelpTopic.IndividualMigration, "Миграция одного сохранения", "Используйте этот режим, когда переносите по одному старому сохранению.\n\n1. Выберите обычный файл сохранения игры: save.json или auto_save.json.\n2. инструмент переноса данных покажет вероятные старые данные Ай-Эм Дата Кор. Выберите предложенный вариант или укажите старый im_data_core.db вручную.\n3. Нажмите Проверить источник, если хотите увидеть, что найдено в старых данных.\n4. Оставьте обычную папку Ай-Эм Дата Кор как место назначения, если специально не тестируете в другом месте.\n5. Сначала выберите Только проверить. Это проверяет план без записи нового сопутствующего файла данных.\n6. Если всё выглядит правильно, выберите Перенести копию.\n7. Откройте место назначения, если хотите увидеть новый файл. При включённой очистке старый источник отправляется в Корзину только после записи и повторной проверки новой копии."),
        new(HelpTopic.ReverseMatching, "Если у вас есть только старый файл Ай-Эм Дата Кор", "Используйте этот способ, если вы нашли старую базу, но не знаете, к какому обычному сохранению она относится.\n\n1. Сначала выберите старый файл Ай-Эм Дата Кор.\n2. Нажмите Проверить источник.\n3. Просканируйте папку данных Айдол Менеджер.\n4. инструмент переноса данных покажет наиболее вероятные сохранения.\n5. Сравните имя сохранения, игрока, группу, дату и путь.\n6. Выберите нужное сохранение.\n7. Перед миграцией выполните проверку."),
        new(HelpTopic.Validation, "Только проверить", "Только проверить — безопасный предварительный просмотр. инструмент переноса данных строит будущие данные в памяти и проверяет их, но не записывает новый сопутствующий файл данных.\n\nУСПЕХ означает, что запланированный файл имеет правильную структуру. Для очень старых версий Ай-Эм Дата Кор может остаться предупреждение о том, что невозможно доказать связь именно с этим сохранением: старые версии не хранили точную контрольную точку. Это предупреждение о достоверности соответствия, а не об ошибке формата данных.\n\nСтарый Ай-Эм Дата Кор мог продолжать сохранять данные, даже если обычный файл сохранения игры не перезаписывался. Поэтому более новая дата базы не означает автоматически повреждение."),
        new(HelpTopic.BranchRepair, "Ремонт загрязнения веток", "Используйте этот режим, если в одной старой базе обнаружено несколько линий прохождения, обычно когда игровая дата резко прыгает назад.\n\n1. Откройте Ремонт загрязнения веток.\n2. Прочитайте список веток и сводку.\n3. Осторожное восстановление сохраняет только ветку, которая лучше всего соответствует выбранному сохранению, и только до даты этого сохранения.\n4. Чистая база сохраняет привязку к обычному сохранению, но удаляет старую историю событий и старое пользовательское состояние. Используйте её, если ветку нельзя выбрать уверенно.\n5. Сначала проверьте ремонт.\n6. Записывайте его только после проверки выбора.\n\nинструмент переноса данных никогда не придумывает отсутствующие события."),
        new(HelpTopic.BulkScan, "Массовое сканирование загрязнения", "Это сканирование проверяет целую папку старых сохранений Ай-Эм Дата Кор перед конвертацией. Старые файлы не изменяются.\n\n1. Выберите корневую папку старых сохранений Ай-Эм Дата Кор.\n2. Нажмите Сканировать.\n3. Дождитесь заполнения таблицы.\n4. Нет сброса ветки означает лишь, что сканирование не увидело прыжка игровой даты назад. Это не гарантия идеальных данных.\n5. Загрязнённая/расходящаяся линия означает, что найден один или несколько прыжков назад.\n6. Выберите строку для просмотра подробностей.\n7. Экспортируйте табличные данные или структурированные данные для отчёта либо откройте Массовую конвертацию."),
        new(HelpTopic.BulkConvert, "Массовая конвертация", "Массовая конвертация планирует много переносов вместе. Она намеренно осторожна и оставляет сомнительные строки для ручной проверки.\n\n1. Выберите корень старых данных, папку данных Айдол Менеджер и выходной корень Ай-Эм Дата Кор.\n2. Выберите способ обработки загрязнённых сохранений. Автоматический ремонт обычно удобнее: подходящая ветка сохраняется при хороших доказательствах, иначе используется чистая база.\n3. Нажмите Построить план. Пока ничего не записывается.\n4. Проверьте столбцы Статус и Подробности.\n5. Разрешите слабые, неоднозначные или отсутствующие соответствия через Разрешить соответствие.\n6. Проверьте строки с обрезкой будущего хвоста.\n7. Нажмите Проверить выбранное для теста без записи.\n8. Нажмите Конвертировать выбранное, когда план вас устраивает.\n9. При необходимости экспортируйте результат."),
        new(HelpTopic.MatchResolver, "Разрешить соответствие", "Это окно позволяет вам выбрать сохранение вручную, если старые данные не указывают на одно сохранение достаточно ясно.\n\nБаллы — подсказка, а не окончательное решение. Соответствие конкретному файлу обычно сильнее старого соответствия по агентству, но ориентируйтесь на знакомые вам данные сохранения.\n\n1. Выберите старую строку в Массовой конвертации.\n2. Нажмите Разрешить соответствие.\n3. Сравните пути, имя игрока, группу, даты и другие сведения.\n4. Выберите правильное сохранение и подтвердите.\n5. Если нужного сохранения нет в списке, укажите его через Обзор.\n\nЕсли после этого две старые базы будут указывать на один выходной файл, инструмент переноса данных попросит подтверждение перед заменой выбора."),
        new(HelpTopic.FutureTail, "Обрезка будущего хвоста", "Старый Ай-Эм Дата Кор мог записывать данные после последнего сохранения обычного слота. Например, вы могли продолжить играть и выйти, не перезаписав ручное сохранение.\n\nЕсли даты событий идут вперёд нормально и просто продолжаются дальше даты обычного сохранения, инструмент переноса данных может предложить обрезку будущего хвоста. Сохраняются события только до даты сохранения, а более поздние удаляются. Старое изменяемое пользовательское состояние не сохраняется, потому что безопасно вернуть его к более раннему моменту невозможно.\n\nЭто не то же самое, что загрязнение веток, где линия времени реально прыгает назад."),
        new(HelpTopic.Cleanup, "Очистка старых данных Ай-Эм Дата Кор", "Очистка необязательна. Безопаснее сначала выполнить миграцию, проверить результат и только затем удалять старое.\n\n• Удаление после успеха разрешается только после записи, повторного открытия и проверки нового файла данных версии 6.\n• Удалить успешно перенесённые отправляет в Корзину только успешные источники.\n• Удалить сиротские источники применяется только к строкам Нет соответствующего сохранения. Слабые и неоднозначные соответствия сиротами не считаются.\n• Файлы отправляются в Корзину Виндоус, а не удаляются безвозвратно.\n• Если старая папка сохранения стала пустой после удаления файлов Ай-Эм Дата Кор, инструмент переноса данных отправляет в Корзину и эту пустую папку.\n• База с несколькими потоками сохранений хранится, пока все зависимые потоки нельзя безопасно удалить."),
        new(HelpTopic.Statuses, "Частые статусы массового плана", "Готово: обычная миграция — найдено пригодное соответствие, план прошёл проверку.\n\nГотово: сохранение ветки — обнаружено несколько линий, и одну ветку можно сохранить с достаточной уверенностью.\n\nГотово: чистая база — обычное сохранение известно, но смешанную историю нельзя безопасно разделить.\n\nГотово: обрезка будущего хвоста — линия непрерывна, но продолжается дальше даты выбранного сохранения.\n\nСлабое соответствие — возможное сохранение найдено, но автоматических доказательств мало. Используйте Разрешить соответствие.\n\nНеоднозначное соответствие — одинаково подходят два или больше сохранений. Используйте Разрешить соответствие.\n\nНет соответствия — подходящее обычное сохранение не найдено. Возможно, оно было удалено или перемещено.\n\nСтарый источник заменён — более сильный источник уже указывает на то же сохранение.\n\nПроверка не пройдена — прочитайте Подробности."),
        new(HelpTopic.Logs, "Журналы и устранение проблем", "Большинству пользователей диагностические журналы не нужны. Открывайте Журналы, если окно не запускается, сканирование завершается ошибкой или нужно точно сообщить, что произошло.\n\nОткрыть место назначения показывает текущую выходную папку Ай-Эм Дата Кор. Это удобно после миграции для проверки наличия нового сопутствующего файла данных.\n\nЕсли предупреждение непонятно, сохраните старые файлы, не запускайте очистку и сначала проверьте строку или отдельную миграцию."),
    };

    private static IReadOnlyList<HelpSection> fr() => new HelpSection[]
    {
        new(HelpTopic.Overview, "À quoi sert l’outil de migration des données IMDataCore", "L’outil de migration des données IMDataCore déplace les anciennes données IMDataCore 1.0.0–1.3.0 vers le format de données actuel version 6, avec le journal de modifications version 3. Il lui faut les anciennes données et, dans la plupart des cas, la sauvegarde Idol Manager normale correspondante.\n\nRien n’est modifié simplement en ouvrant, inspectant ou analysant un fichier, ni avec Valider seulement. L’écriture ne se produit que lorsque vous choisissez une migration ou une réparation."),
        new(HelpTopic.BeforeYouStart, "Avant de commencer", "1. Fermez Idol Manager avant d'écrire des données migrées.\n2. Gardez une copie de vos anciennes sauvegardes et dossiers IMDataCore jusqu'à ce que vous ayez vérifié le nouveau résultat.\n3. Utilisez si possible la sauvegarde Idol Manager normale qui correspond aux anciennes données IMDataCore.\n4. Si l’outil de migration des données n'est pas sûr d'une correspondance, vérifiez-la au lieu de deviner.\n5. Le nettoyage est facultatif. l’outil de migration des données peut envoyer les anciennes données dans la Corbeille Windows après une migration réussie."),
        new(HelpTopic.IndividualMigration, "Migration individuelle", "Utilisez ceci pour déplacer une ancienne sauvegarde à la fois.\n\n1. Choisissez la sauvegarde de jeu brute, c'est-à-dire le save.json ou auto_save.json normal d'Idol Manager.\n2. l’outil de migration des données affiche les anciennes données IMDataCore probables. Choisissez une suggestion ou parcourez manuellement vers l'ancien im_data_core.db.\n3. Utilisez Inspecter si vous voulez voir ce que l’outil de migration des données a trouvé.\n4. Laissez la destination dans le dossier IMDataCore normal sauf si vous faites volontairement un test ailleurs.\n5. Choisissez d'abord Valider seulement. Cela vérifie la conversion sans écrire le nouveau sidecar.\n6. Si le résultat convient, choisissez Migrer une copie.\n7. Ouvrez la destination si vous voulez voir le nouveau fichier. Si le nettoyage est activé, l'ancienne source n'est recyclée qu'après écriture et nouvelle vérification de la sortie."),
        new(HelpTopic.ReverseMatching, "Commencer par un ancien fichier IMDataCore", "Utilisez ceci si vous avez trouvé une ancienne base mais ne savez pas quelle sauvegarde normale lui appartient.\n\n1. Sélectionnez d'abord l'ancien fichier IMDataCore.\n2. Choisissez Inspecter.\n3. Analysez le dossier data d'Idol Manager pour trouver les sauvegardes normales.\n4. l’outil de migration des données liste les sauvegardes qui semblent les plus probables.\n5. Vérifiez le nom, le joueur, le groupe, la date et le chemin.\n6. Choisissez Utiliser la sauvegarde quand vous trouvez la bonne.\n7. Validez avant de migrer."),
        new(HelpTopic.Validation, "Valider seulement", "Valider seulement est l'aperçu sûr. l’outil de migration des données construit en mémoire les données au format actuel et les vérifie, sans écrire le sidecar migré.\n\nSUCCÈS signifie que la sortie prévue est structurellement valide. Pour les très anciennes versions d'IMDataCore, l’outil de migration des données peut encore avertir qu'il ne peut pas prouver que la base vient exactement de cette sauvegarde, car ces versions n'enregistraient pas de point de contrôle exact. Cet avertissement concerne la certitude de la correspondance, pas le format JSON.\n\nL'ancien IMDataCore pouvait continuer à sauvegarder alors que le fichier de sauvegarde normal n'était pas réécrit. Une base plus récente que la sauvegarde n'est donc pas automatiquement mauvaise."),
        new(HelpTopic.BranchRepair, "Réparer la contamination de branches", "Utilisez ceci lorsque l’outil de migration des données trouve plusieurs lignes de jeu dans une ancienne base, généralement lorsque la date en jeu revient en arrière.\n\n1. Ouvrez Réparer la contamination de branches.\n2. Lisez la liste des branches et le résumé.\n3. La récupération prudente garde uniquement la branche qui correspond le mieux à la sauvegarde choisie, jusqu'à la date de cette sauvegarde.\n4. La base propre conserve le lien avec la sauvegarde mais supprime l'ancien historique d'événements et l'ancien état personnalisé. Utilisez-la si aucune branche ne peut être choisie avec confiance.\n5. Validez d'abord la réparation.\n6. Écrivez-la seulement après avoir vérifié votre choix.\n\noutil de migration des données n'invente jamais les événements manquants."),
        new(HelpTopic.BulkScan, "Analyse en masse de contamination", "Cette analyse vérifie tout un dossier d'anciennes sauvegardes IMDataCore avant conversion. Elle ne modifie pas les anciens fichiers.\n\n1. Choisissez la racine des anciennes sauvegardes IMDataCore.\n2. Choisissez Analyser.\n3. Attendez que le tableau soit rempli.\n4. Aucun retour de branche détecté signifie seulement qu'aucun saut en arrière de la date en jeu n'a été vu. Ce n'est pas une garantie que tout est parfait.\n5. Chronologie contaminée/divergente signifie qu'un ou plusieurs retours en arrière ont été trouvés.\n6. Sélectionnez une ligne pour lire les détails.\n7. Exportez en CSV ou JSON si vous voulez un rapport, ou ouvrez Conversion en masse pour planifier les migrations."),
        new(HelpTopic.BulkConvert, "Conversion en masse", "La conversion en masse planifie plusieurs migrations ensemble. Elle est volontairement prudente et garde les lignes incertaines pour votre vérification.\n\n1. Choisissez la racine héritée, la racine data d'Idol Manager et la racine IMDataCore de destination.\n2. Choisissez comment traiter les sauvegardes contaminées. La réparation automatique est généralement adaptée : elle récupère une branche quand les indices sont bons, sinon utilise une base propre.\n3. Choisissez Construire le plan. Rien n'est encore écrit.\n4. Vérifiez les colonnes État et Détails.\n5. Résolvez les correspondances faibles, ambiguës ou absentes avec Résoudre la correspondance.\n6. Vérifiez les lignes de troncature de fin future.\n7. Choisissez Valider la sélection pour un test sans écriture.\n8. Choisissez Convertir la sélection quand le plan vous convient.\n9. Exportez le résultat si vous voulez garder une trace."),
        new(HelpTopic.MatchResolver, "Résoudre la correspondance", "Le résolveur vous laisse faire le choix final lorsque les anciennes données n'identifient pas assez clairement une seule sauvegarde normale.\n\nLes scores sont des indices, pas un verdict. Une correspondance propre à un fichier est normalement plus forte qu'une ancienne correspondance d'agence, mais servez-vous surtout des détails que vous reconnaissez.\n\n1. Sélectionnez la ligne héritée dans Conversion en masse.\n2. Choisissez Résoudre la correspondance.\n3. Comparez les chemins, le joueur, le groupe, les dates et les autres détails.\n4. Sélectionnez la bonne sauvegarde et confirmez.\n5. Si elle n'est pas listée, utilisez Parcourir la sauvegarde pour la choisir directement.\n\nSi deux anciennes bases visent alors la même sortie, l’outil de migration des données demande avant de remplacer le choix existant."),
        new(HelpTopic.FutureTail, "Tronquer une fin future", "L'ancien IMDataCore pouvait enregistrer des données après la dernière sauvegarde de ce slot normal. Par exemple, vous pouviez continuer à jouer puis quitter sans réécrire une sauvegarde manuelle.\n\nLorsque les dates avancent normalement et continuent simplement au-delà de la date de la sauvegarde, l’outil de migration des données peut proposer de tronquer la fin future. Il garde les événements jusqu'à la date de la sauvegarde et retire les événements ultérieurs. L'ancien état personnalisé modifiable n'est pas conservé, car l’outil de migration des données ne peut pas le ramener de façon sûre à l'instant précédent.\n\nC'est différent d'une contamination de branches, où la chronologie revient réellement en arrière."),
        new(HelpTopic.Cleanup, "Nettoyer les anciennes données IMDataCore", "Le nettoyage est facultatif. Il est plus sûr de migrer, vérifier le résultat, puis nettoyer.\n\n• Recycler après succès n'est possible qu'après écriture, réouverture et nouvelle validation de la sortie v6.\n• Recycler les migrations réussies supprime les sources qui ont réussi.\n• Recycler les sources orphelines concerne uniquement les lignes réellement Sans correspondance de sauvegarde. Les correspondances faibles ou ambiguës ne sont pas des orphelins.\n• Les fichiers vont dans la Corbeille Windows au lieu d'être supprimés définitivement.\n• Si le dossier de l'ancienne sauvegarde devient vide après recyclage des fichiers IMDataCore, l’outil de migration des données recycle aussi ce dossier vide.\n• Une base contenant plusieurs flux de sauvegarde est gardée jusqu'à ce que chacun puisse être supprimé en sécurité."),
        new(HelpTopic.Statuses, "États courants du plan en masse", "Prêt : migration normale — la correspondance est utilisable et le plan a passé la validation.\n\nPrêt : récupération de branche — plusieurs chronologies existent et une branche peut être gardée avec assez de confiance.\n\nPrêt : base propre — la sauvegarde est connue, mais l'historique mélangé ne peut pas être séparé sans risque.\n\nPrêt : troncature de fin future — la chronologie est continue mais dépasse la date de la sauvegarde sélectionnée.\n\nCorrespondance faible — une sauvegarde possible a été trouvée, mais les indices automatiques ne suffisent pas. Utilisez Résoudre la correspondance.\n\nCorrespondance ambiguë — plusieurs sauvegardes semblent aussi bonnes. Utilisez Résoudre la correspondance.\n\nAucune correspondance — aucune sauvegarde normale reconnue ne correspond. L'ancienne sauvegarde a peut-être été supprimée ou déplacée.\n\nSource héritée remplacée — une source ancienne plus forte vise déjà la même sauvegarde.\n\nÉchec de validation — lisez Détails avant de continuer."),
        new(HelpTopic.Logs, "Journaux et dépannage", "La plupart des utilisateurs n'ont pas besoin des journaux de diagnostic. Utilisez Journaux si une fenêtre échoue, si une analyse produit une erreur ou si vous devez signaler exactement ce qui s'est passé.\n\nOuvrir la destination ouvre le dossier de sortie IMDataCore actuel. C'est utile après une migration pour confirmer que le nouveau sidecar existe.\n\nSi un avertissement n'est pas clair, gardez les anciens fichiers, ne forcez pas le nettoyage et vérifiez la ligne ou la migration individuelle avant de continuer."),
    };

    private static IReadOnlyList<HelpSection> ja() => new HelpSection[]
    {
        new(HelpTopic.Overview, "データ移行ツールでできること", "このデータ移行ツールは、旧アイエムデータコア 1.0.0～1.3.0 のデータを現在の第6版データ形式へ移行します。現在の履歴記録形式は第3版です。通常は古いデータと、それに対応する通常のアイドルマネージャーセーブが必要です。\n\nファイルを開く、調べる、スキャンする、または「検証のみ」を使うだけでは何も変更されません。実際に書き込むのは、移行または修復を実行したときだけです。"),
        new(HelpTopic.BeforeYouStart, "始める前に", "1. 移行データを書き込む前に アイドルマネージャー を終了してください。\n2. 新しい結果を確認するまでは、古いセーブと古い アイエムデータコア フォルダーのバックアップを残してください。\n3. できるだけ、その古い アイエムデータコア データに対応する通常の アイドルマネージャー セーブを使ってください。\n4. 対応関係が不確かな場合は、自動で決めつけず内容を確認してください。\n5. 古いデータの整理は任意です。移行成功後に ウィンドウズ のごみ箱へ送ることができます。"),
        new(HelpTopic.IndividualMigration, "1件ずつ移行する", "古いセーブを1件ずつ移行したいときに使います。\n\n1. 通常のゲームセーブを選びます。アイドルマネージャー の save.json または auto_save.json です。\n2. データ移行ツール が候補の古い アイエムデータコア データを表示します。候補を選ぶか、古い im_data_core.db を自分で指定します。\n3. 古いデータの内容を確認したい場合は「検査」を使います。\n4. 特別なテストをしない限り、出力先は通常の アイエムデータコア フォルダーのままにします。\n5. まず「検証のみ」を実行します。新しい 付随データファイル は書き込まず、変換予定だけを確認します。\n6. 問題なければ「コピーを移行」を実行します。\n7. 新しいファイルを確認したい場合は出力先を開きます。整理を有効にしていても、古い元データは新しい出力が書き込まれ、再確認された後でのみごみ箱へ送られます。"),
        new(HelpTopic.ReverseMatching, "古い アイエムデータコア ファイルから探す", "古いデータベースは見つかったものの、どの通常セーブに対応するか分からない場合に使います。\n\n1. 先に古い アイエムデータコア ファイルを選びます。\n2. 「検査」を選びます。\n3. アイドルマネージャー の データ フォルダーをスキャンします。\n4. データ移行ツール が対応していそうなセーブを一覧表示します。\n5. セーブ名、プレイヤー、グループ、日付、パスを確認します。\n6. 正しいセーブを見つけたら使用します。\n7. 移行前に検証してください。"),
        new(HelpTopic.Validation, "検証のみ", "「検証のみ」は安全な事前確認です。現在形式の予定データをメモリ上で作って確認しますが、移行先の 付随データファイル は書き込みません。\n\n成功 は、予定されている出力の構造が正しいことを意味します。非常に古い アイエムデータコア では、正確なチェックポイントを保存していなかったため、そのデータベースが本当にそのセーブから来たものか証明できないという警告が出ることがあります。これは 構造化データ の形式エラーではなく、対応関係の確実さについての警告です。\n\n古い アイエムデータコア は、通常のセーブファイルを上書きしていなくても記録を続けることがありました。そのため、データベースの方が新しいだけで壊れているとは限りません。"),
        new(HelpTopic.BranchRepair, "分岐混在を修復する", "1つの古いデータベースに複数のプレイ履歴が混ざっている場合に使います。多くの場合、ゲーム内の日付が突然過去へ戻ることで見つかります。\n\n1. 「分岐混在を修復」を開きます。\n2. 分岐一覧と概要を読みます。\n3. 保守的な分岐救出では、選んだ通常セーブに最も合う分岐だけを、そのセーブの日付まで残します。\n4. クリーンな基準状態では通常セーブとの結び付けだけを残し、古いイベント履歴と古いカスタム状態を捨てます。分岐を自信を持って選べないときに使います。\n5. まず修復内容を検証します。\n6. 選択に納得してから書き込みます。\n\nデータ移行ツール が不足しているイベントを作り出すことはありません。"),
        new(HelpTopic.BulkScan, "一括混在スキャン", "古い アイエムデータコア セーブのフォルダー全体を、変換前に確認するためのスキャンです。古いファイルは変更しません。\n\n1. 古い アイエムデータコア セーブのルートを選びます。\n2. スキャンを実行します。\n3. 表の読み込みが終わるまで待ちます。\n4. 分岐リセットなしは、ゲーム内日付が過去へ飛ぶ現象が見つからなかったという意味だけです。完全に問題がない保証ではありません。\n5. 汚染/分岐したタイムラインは、過去へのジャンプが1つ以上見つかった状態です。\n6. 行を選ぶと詳細を読めます。\n7. 必要なら 表形式データ/構造化データ を出力するか、「一括変換」を開いて移行計画を作ります。"),
        new(HelpTopic.BulkConvert, "一括変換", "一括変換では、多数の移行をまとめて計画します。不確かな行を勝手に処理せず、確認待ちにするよう慎重に動きます。\n\n1. 古いデータのルート、アイドルマネージャー の データ ルート、出力先 アイエムデータコア ルートを選びます。\n2. 汚染セーブの扱いを選びます。通常は自動修復が便利で、証拠が十分なら分岐を救出し、不十分ならクリーンな基準状態を使います。\n3. 計画を作成します。この時点では書き込みません。\n4. 状態と詳細を確認します。\n5. 弱い一致、あいまいな一致、見つからない一致は「一致を解決」で確認します。\n6. 将来側の末尾を切り詰める行も確認します。\n7. 「選択項目を検証」で書き込みなしのテストをします。\n8. 計画に納得したら「選択項目を変換」を実行します。\n9. 必要なら結果を出力して記録を残します。"),
        new(HelpTopic.MatchResolver, "一致を解決する", "古いデータだけでは1つの通常セーブに絞れないとき、最終的にユーザーが選ぶための画面です。\n\n一致スコアは手掛かりであり、絶対的な判定ではありません。ファイル単位の一致は古いエージェンシー単位の一致より通常は強いですが、自分が分かるセーブ情報も確認してください。\n\n1. 一括変換で古いデータの行を選びます。\n2. 「一致を解決」を選びます。\n3. セーブのパス、プレイヤー名、グループ名、日付などを比較します。\n4. 正しいセーブを選んで確定します。\n5. 正しいセーブが一覧にない場合は、参照から直接指定します。\n\n2つの古いデータベースが同じ出力先を使うことになる場合、データ移行ツール は既存の計画を置き換える前に確認します。"),
        new(HelpTopic.FutureTail, "将来側の末尾を切り詰める", "古い アイエムデータコア は、その通常セーブを最後に保存した後も記録を続けることがありました。たとえば、手動セーブを上書きせずにしばらく遊び、そのまま終了した場合です。\n\nイベントの日付が正常に前へ進み、単に通常セーブの日付を越えて続いているだけなら、データ移行ツール は将来側の末尾切り詰めを提案できます。通常セーブの日付までのイベントだけを残し、それより後を削ります。古い可変カスタムデータは、その時点まで安全に巻き戻せないため保持しません。\n\nこれは、タイムライン自体が過去へ戻る分岐混在とは別の状態です。"),
        new(HelpTopic.Cleanup, "古い アイエムデータコア データを整理する", "整理は任意です。まず移行し、結果を確認してから整理する方が安全です。\n\n• 成功後にごみ箱へ送る処理は、新しい 第6版 出力が書き込まれ、再度開いて検証された後でのみ実行できます。\n• 成功した移行を整理すると、成功済みの元データを対象にします。\n• 孤立した元データの整理は、本当に「通常セーブ一致なし」の行だけが対象です。弱い一致やあいまいな一致は孤立扱いにしません。\n• ファイルは完全削除ではなく ウィンドウズ のごみ箱へ送られます。\n• 古いセーブ用フォルダーが空になった場合、その空フォルダーもごみ箱へ送られます。\n• 複数のセーブ履歴を含む1つのデータベースは、必要な全履歴を安全に片付けられるまで残されます。"),
        new(HelpTopic.Statuses, "一括計画でよく出る状態", "準備完了: 通常移行 — 古いデータと通常セーブの対応が使え、計画も検証に通っています。\n\n準備完了: 分岐救出 — 複数のタイムラインがあり、十分な確度で残せる分岐があります。\n\n準備完了: クリーン基準状態 — 通常セーブは分かっていますが、混ざった履歴を安全に分離できません。\n\n準備完了: 将来末尾の切り詰め — タイムラインは連続していますが、選択した通常セーブの日付より先まで続いています。\n\n弱い一致 — 候補はありますが、自動判定の根拠が弱い状態です。「一致を解決」を使います。\n\nあいまいな一致 — 同じくらい良い候補が複数あります。「一致を解決」を使います。\n\n通常セーブ一致なし — 認識できる通常セーブが見つかりません。古いセーブが削除または移動されている可能性があります。\n\n古い元データが置換済み — より強い古い元データが同じ通常セーブをすでに使っています。\n\n検証失敗 — 続行前に詳細欄を読んでください。"),
        new(HelpTopic.Logs, "ログとトラブル対応", "通常は診断ログを見る必要はありません。画面が開かない、スキャンでエラーが出る、発生した内容を正確に報告したい場合に「ログ」を使ってください。\n\n「出力先を開く」は現在の アイエムデータコア 出力フォルダーを開きます。移行後に新しい 付随データファイル が作られたか確認するときに便利です。\n\n警告の意味が分からない場合は、古いファイルを残し、整理を強制せず、該当行または個別移行を確認してから続けてください。"),
    };

    private static IReadOnlyList<HelpSection> ko() => new HelpSection[]
    {
        new(HelpTopic.Overview, "데이터 이전 도구의 용도", "이 데이터 이전 도구는 이전 아이엠데이터코어 1.0.0–1.3.0 데이터를 현재 6판 데이터 형식으로 옮깁니다. 현재 변경 기록 형식은 3판입니다. 보통 이전 데이터와 그에 대응하는 일반 아이돌 매니저 저장 파일이 필요합니다.\n\n파일을 열거나 검사하거나 스캔하거나 검증만 실행하는 것만으로는 아무것도 변경되지 않습니다. 실제 쓰기는 이전이나 복구 작업을 선택했을 때만 일어납니다."),
        new(HelpTopic.BeforeYouStart, "시작하기 전에", "1. 마이그레이션 데이터를 쓰기 전에 아이돌 매니저를 종료하세요.\n2. 새 결과를 확인할 때까지 오래된 저장 파일과 아이엠데이터코어 폴더의 백업을 보관하세요.\n3. 가능하면 오래된 아이엠데이터코어 데이터와 실제로 짝이 되는 일반 아이돌 매니저 저장 파일을 사용하세요.\n4. 데이터 이전 도구가 매치를 확신하지 못하면 추측하지 말고 직접 확인하세요.\n5. 정리는 선택 사항입니다. 성공한 마이그레이션 뒤에 오래된 데이터를 윈도우 휴지통으로 보낼 수 있습니다."),
        new(HelpTopic.IndividualMigration, "개별 마이그레이션", "오래된 저장을 하나씩 옮길 때 사용합니다.\n\n1. 일반 게임 저장을 선택합니다. 아이돌 매니저의 save.json 또는 auto_save.json입니다.\n2. 데이터 이전 도구가 가능성이 높은 오래된 아이엠데이터코어 데이터를 보여 줍니다. 제안된 항목을 선택하거나 오래된 im_data_core.db를 직접 찾으세요.\n3. 오래된 데이터에서 무엇을 찾았는지 보고 싶다면 검사를 사용하세요.\n4. 특별히 테스트하는 경우가 아니라면 대상은 일반 아이엠데이터코어 폴더로 두세요.\n5. 먼저 검증만을 실행하세요. 새 동반 데이터 파일을 쓰지 않고 변환 계획만 검사합니다.\n6. 결과가 맞아 보이면 복사본 마이그레이션을 실행하세요.\n7. 새 파일을 확인하려면 대상을 여세요. 정리가 켜져 있어도 새 출력이 쓰이고 다시 검증된 뒤에만 오래된 원본이 휴지통으로 갑니다."),
        new(HelpTopic.ReverseMatching, "오래된 아이엠데이터코어 파일에서 시작하기", "오래된 데이터베이스는 찾았지만 어떤 일반 저장과 짝인지 모를 때 사용합니다.\n\n1. 먼저 오래된 아이엠데이터코어 파일을 선택합니다.\n2. 검사를 선택합니다.\n3. 아이돌 매니저 데이터 폴더에서 일반 저장을 스캔합니다.\n4. 데이터 이전 도구가 가능성이 높은 저장을 목록으로 보여 줍니다.\n5. 저장 이름, 플레이어, 그룹, 날짜, 경로를 비교하세요.\n6. 올바른 저장을 찾으면 사용하세요.\n7. 마이그레이션 전에 검증하세요."),
        new(HelpTopic.Validation, "검증만", "검증만은 안전한 미리보기입니다. 현재 형식의 계획 데이터를 메모리에서 만들고 검사하지만, 마이그레이션 동반 데이터 파일를 쓰지는 않습니다.\n\n성공는 계획된 출력 구조가 올바르다는 뜻입니다. 매우 오래된 아이엠데이터코어 버전은 정확한 체크포인트를 저장하지 않았기 때문에, 그 데이터베이스가 정확히 그 저장에서 나온 것인지 증명할 수 없다는 경고가 남을 수 있습니다. 이 경고는 구조화 데이터 형식이 아니라 매치의 확실성에 관한 것입니다.\n\n오래된 아이엠데이터코어는 일반 저장 파일을 덮어쓰지 않아도 계속 데이터를 저장할 수 있었습니다. 따라서 데이터베이스가 일반 저장보다 최신이라고 해서 자동으로 잘못된 데이터인 것은 아닙니다."),
        new(HelpTopic.BranchRepair, "브랜치 오염 복구", "한 오래된 데이터베이스 안에 여러 플레이 타임라인이 섞여 있을 때 사용합니다. 보통 게임 날짜가 갑자기 과거로 돌아갈 때 발견됩니다.\n\n1. 브랜치 오염 복구를 엽니다.\n2. 브랜치 목록과 요약을 읽습니다.\n3. 보수적 브랜치 복구는 선택한 일반 저장과 가장 잘 맞는 브랜치만 그 저장 날짜까지 유지합니다.\n4. 깨끗한 기준선은 일반 저장과의 연결은 유지하지만 오래된 이벤트 기록과 오래된 사용자 상태는 버립니다. 어떤 브랜치도 자신 있게 고를 수 없을 때 사용하세요.\n5. 먼저 복구를 검증하세요.\n6. 선택이 맞다고 확인한 뒤에만 복구를 쓰세요.\n\n데이터 이전 도구는 없는 이벤트를 만들어 내지 않습니다."),
        new(HelpTopic.BulkScan, "대량 오염 스캔", "변환 전에 오래된 아이엠데이터코어 저장 폴더 전체를 확인하는 스캔입니다. 오래된 파일은 수정하지 않습니다.\n\n1. 오래된 아이엠데이터코어 저장 루트를 선택합니다.\n2. 스캔을 실행합니다.\n3. 표가 모두 채워질 때까지 기다립니다.\n4. 브랜치 리셋 감지 안 됨은 게임 날짜가 뒤로 뛰는 현상을 찾지 못했다는 뜻일 뿐, 데이터가 완벽하다는 보장은 아닙니다.\n5. 오염/분기된 타임라인은 하나 이상의 뒤로 가는 점프가 발견된 상태입니다.\n6. 행을 선택해 세부 정보를 읽으세요.\n7. 보고서가 필요하면 표 형식 데이터/구조화 데이터으로 내보내거나 대량 변환을 열어 계획을 만드세요."),
        new(HelpTopic.BulkConvert, "대량 변환", "대량 변환은 여러 마이그레이션을 함께 계획합니다. 불확실한 행을 마음대로 처리하지 않고 사용자가 검토하도록 남겨 두도록 설계되어 있습니다.\n\n1. 오래된 데이터 루트, 아이돌 매니저 데이터 루트, 출력 아이엠데이터코어 루트를 선택합니다.\n2. 오염 저장 처리 방법을 선택합니다. 자동 복구는 보통 좋은 선택이며, 근거가 충분하면 브랜치를 살리고 그렇지 않으면 깨끗한 기준선을 사용합니다.\n3. 계획 만들기를 선택합니다. 아직 아무것도 쓰지 않습니다.\n4. 상태와 세부 정보 열을 확인합니다.\n5. 약한 매치, 모호한 매치, 누락된 매치는 매치 해결로 확인합니다.\n6. 미래 꼬리 자르기 행도 검토합니다.\n7. 선택 항목 검증으로 쓰기 없는 테스트를 합니다.\n8. 계획이 맞으면 선택 항목 변환을 실행합니다.\n9. 기록이 필요하면 결과를 내보내세요."),
        new(HelpTopic.MatchResolver, "매치 해결", "오래된 데이터만으로 하나의 일반 저장을 명확히 고를 수 없을 때 사용자가 최종 선택을 하는 창입니다.\n\n매치 점수는 힌트이지 판결이 아닙니다. 파일 전용 매치는 오래된 에이전시 단위 매치보다 보통 강하지만, 본인이 알아볼 수 있는 저장 정보도 함께 확인하세요.\n\n1. 대량 변환에서 오래된 데이터 행을 선택합니다.\n2. 매치 해결을 선택합니다.\n3. 저장 경로, 플레이어 이름, 그룹 이름, 날짜 등을 비교합니다.\n4. 올바른 저장을 선택하고 확인합니다.\n5. 올바른 저장이 목록에 없으면 찾아보기를 사용해 직접 지정합니다.\n\n두 오래된 데이터베이스가 같은 출력으로 향하게 되면 데이터 이전 도구가 기존 계획 선택을 바꾸기 전에 확인을 요청합니다."),
        new(HelpTopic.FutureTail, "미래 꼬리 자르기", "오래된 아이엠데이터코어는 일반 저장 슬롯을 마지막으로 저장한 뒤에도 데이터를 기록할 수 있었습니다. 예를 들어 수동 저장을 덮어쓰지 않고 계속 플레이한 뒤 종료할 수 있습니다.\n\n이벤트 날짜가 정상적으로 앞으로 진행하면서 단순히 일반 저장 날짜를 지나 계속되는 경우 데이터 이전 도구는 미래 꼬리 자르기를 제안할 수 있습니다. 일반 저장 날짜까지의 이벤트만 유지하고 이후 부분은 제거합니다. 오래된 변경 가능한 사용자 데이터는 이전 시점으로 안전하게 되돌릴 수 없기 때문에 유지하지 않습니다.\n\n이는 타임라인 자체가 과거로 뛰는 브랜치 오염과는 다릅니다."),
        new(HelpTopic.Cleanup, "오래된 아이엠데이터코어 데이터 정리", "정리는 선택 사항입니다. 먼저 마이그레이션하고 결과를 확인한 다음 정리하는 것이 더 안전합니다.\n\n• 성공 후 휴지통 처리는 새 6판 출력이 쓰이고, 다시 열리고, 다시 검증된 뒤에만 가능해집니다.\n• 성공한 마이그레이션 정리는 성공한 원본만 처리합니다.\n• 고아 원본 정리는 실제로 일반 저장 매치 없음인 행에만 적용됩니다. 약하거나 모호한 매치는 고아로 보지 않습니다.\n• 파일은 영구 삭제가 아니라 윈도우 휴지통으로 갑니다.\n• 오래된 저장 폴더가 아이엠데이터코어 파일 정리 후 비게 되면 그 빈 폴더도 휴지통으로 갑니다.\n• 여러 저장 스트림이 들어 있는 데이터베이스는 필요한 모든 스트림을 안전하게 정리할 수 있을 때까지 유지됩니다."),
        new(HelpTopic.Statuses, "대량 계획의 일반적인 상태", "준비됨: 일반 마이그레이션 — 사용할 수 있는 매치가 있고 계획이 검증을 통과했습니다.\n\n준비됨: 브랜치 복구 — 여러 타임라인이 있으며 충분한 확신으로 유지할 브랜치가 있습니다.\n\n준비됨: 깨끗한 기준선 — 일반 저장은 알지만 섞인 기록을 안전하게 나눌 수 없습니다.\n\n준비됨: 미래 꼬리 자르기 — 타임라인은 연속적이지만 선택한 일반 저장 날짜 이후까지 이어집니다.\n\n약한 매치 — 후보는 있지만 자동 근거가 충분히 강하지 않습니다. 매치 해결을 사용하세요.\n\n모호한 매치 — 둘 이상의 저장이 비슷하게 잘 맞습니다. 매치 해결을 사용하세요.\n\n일반 저장 매치 없음 — 인식된 일반 저장 중 맞는 항목이 없습니다. 오래된 저장이 삭제되었거나 이동되었을 수 있습니다.\n\n대체된 오래된 원본 — 더 강한 오래된 원본이 이미 같은 일반 저장을 대상으로 합니다.\n\n검증 실패 — 계속하기 전에 세부 정보를 읽으세요."),
        new(HelpTopic.Logs, "로그와 문제 해결", "대부분의 사용자는 진단 로그가 필요하지 않습니다. 창이 열리지 않거나 스캔 오류가 생기거나 무슨 일이 있었는지 정확히 보고해야 할 때 로그를 사용하세요.\n\n대상 열기는 현재 아이엠데이터코어 출력 폴더를 엽니다. 마이그레이션 후 새 동반 데이터 파일이 있는지 확인할 때 유용합니다.\n\n경고가 이해되지 않으면 오래된 파일을 남겨 두고 정리를 강제로 실행하지 말고, 해당 행이나 개별 마이그레이션을 먼저 검토하세요."),
    };

    private static IReadOnlyList<HelpSection> zh_Hans() => new HelpSection[]
    {
        new(HelpTopic.Overview, "数据迁移工具是做什么的", "这个数据迁移工具把旧版偶像经理数据核心 1.0.0–1.3.0 数据迁移到当前第6版数据格式，当前变更记录格式为第3版。通常需要旧数据，以及与它对应的普通偶像经理存档。\n\n仅仅打开、检查或扫描文件，或者使用“仅验证”，都不会修改数据。只有在你选择迁移或修复操作时才会真正写入文件。"),
        new(HelpTopic.BeforeYouStart, "开始之前", "1. 写入迁移数据前，请先关闭 偶像经理。\n2. 在确认新结果正常之前，请保留旧存档和旧 偶像经理数据核心 文件夹的备份。\n3. 尽量使用真正对应这些旧 偶像经理数据核心 数据的普通 偶像经理 存档。\n4. 如果 数据迁移工具 对匹配没有把握，请人工确认，不要让它猜。\n5. 清理旧数据是可选的。成功迁移后，数据迁移工具 可以把旧数据送到 微软视窗系统回收站。"),
        new(HelpTopic.IndividualMigration, "单个存档迁移", "适合一次迁移一个旧存档。\n\n1. 选择普通游戏存档，也就是 偶像经理 的 save.json 或 auto_save.json。\n2. 数据迁移工具 会显示可能对应的旧 偶像经理数据核心 数据。可以选择推荐项，也可以手动找到旧的 im_data_core.db。\n3. 如果想先看看旧数据里有什么，可以使用“检查”。\n4. 除非你特意在别处测试，否则目标位置保持为正常 偶像经理数据核心 文件夹。\n5. 先使用“仅验证”。它会检查计划中的转换，但不会写入新的 伴随数据文件。\n6. 结果看起来正确后，再使用“迁移副本”。\n7. 想查看新文件时可以打开目标位置。即使启用了清理，旧源数据也只会在新输出写入并再次验证成功后才送入回收站。"),
        new(HelpTopic.ReverseMatching, "从旧 偶像经理数据核心 文件开始", "如果你找到了旧数据库，但不知道它属于哪个普通存档，可以用这个流程。\n\n1. 先选择旧 偶像经理数据核心 文件。\n2. 选择“检查”。\n3. 扫描 偶像经理 的 游戏数据 文件夹。\n4. 数据迁移工具 会列出最可能对应的普通存档。\n5. 对比存档名、玩家、组合、日期和路径。\n6. 找到正确存档后选择使用它。\n7. 迁移前先验证。"),
        new(HelpTopic.Validation, "仅验证", "“仅验证”是安全的预览。数据迁移工具 会在内存中生成计划中的当前格式数据并检查它，但不会写入迁移后的 伴随数据文件。\n\n成功 表示计划中的输出结构有效。对于很老的 偶像经理数据核心 版本，数据迁移工具 仍可能提示无法证明旧数据库一定来自这个存档，因为这些版本没有保存精确检查点。这个警告说的是匹配关系的确定程度，不是 结构化数据 格式错误。\n\n旧 偶像经理数据核心 可能在普通存档文件没有被覆盖的情况下继续保存数据。因此，数据库日期比普通存档更新，并不自动说明数据有问题。"),
        new(HelpTopic.BranchRepair, "修复分支混入", "当一个旧数据库里混有多个游玩时间线时使用。常见表现是游戏内日期突然向过去跳。\n\n1. 打开“修复分支混入”。\n2. 阅读分支列表和摘要。\n3. 保守分支保留会只留下与所选普通存档最匹配的分支，并且只保留到该存档日期。\n4. 干净基线会保留与普通存档的绑定，但丢弃旧事件历史和旧自定义状态。无法可靠选择分支时使用它。\n5. 先验证修复。\n6. 确认选择正确后再写入修复。\n\n数据迁移工具 不会编造缺失事件。"),
        new(HelpTopic.BulkScan, "批量污染扫描", "用于在转换前检查整个旧 偶像经理数据核心 存档文件夹。扫描不会修改旧文件。\n\n1. 选择旧 偶像经理数据核心 存档根目录。\n2. 选择“扫描”。\n3. 等待表格填写完成。\n4. “未检测到分支重置”只表示扫描没有看到游戏内日期向过去跳，不代表数据一定完全正常。\n5. “污染/分歧时间线”表示发现了一个或多个向过去的跳转。\n6. 选择一行可查看详细信息。\n7. 需要报告时可导出 表格数据/结构化数据，也可以打开“批量转换”开始规划迁移。"),
        new(HelpTopic.BulkConvert, "批量转换", "批量转换会一次规划多个迁移。它会刻意保持谨慎，把不确定的项目留给你确认，而不是自行猜测。\n\n1. 选择旧数据根目录、偶像经理 的 游戏数据 根目录和目标 偶像经理数据核心 根目录。\n2. 选择如何处理污染存档。通常可用自动修复：证据充分时保留分支，否则使用干净基线。\n3. 选择“生成计划”。此时还不会写入任何文件。\n4. 查看“状态”和“详细信息”。\n5. 对弱匹配、歧义匹配或无匹配项目使用“解决匹配”。\n6. 查看未来尾部截断项目。\n7. 使用“验证所选项”进行不写入的测试。\n8. 确认计划正确后使用“转换所选项”。\n9. 如果需要记录，可导出结果。"),
        new(HelpTopic.MatchResolver, "解决匹配", "当旧数据不足以明确指出唯一普通存档时，这个窗口让你做最终选择。\n\n匹配分数只是线索，不是最终裁定。文件级匹配通常比旧的机构级匹配更强，但仍应结合你认识的存档信息判断。\n\n1. 在批量转换中选择旧数据行。\n2. 选择“解决匹配”。\n3. 对比候选存档的路径、玩家名、组合名、日期和其他信息。\n4. 选择正确存档并确认。\n5. 如果正确存档不在列表中，使用“浏览存档”直接指定。\n\n如果这样会让两个旧数据库指向同一个输出，数据迁移工具 会在替换已有计划选择前询问你。"),
        new(HelpTopic.FutureTail, "截断未来尾部", "旧 偶像经理数据核心 可能会在你最后一次保存普通存档槽之后继续记录数据。例如，你继续玩了一段时间，然后没有覆盖手动存档就退出。\n\n如果事件日期一直正常向前，只是超过了普通存档的日期，数据迁移工具 可以提供“未来尾部截断”。它会只保留到普通存档日期为止的事件，并移除之后的尾部。旧的可变自定义数据不会保留，因为无法安全地把这些值倒回较早时刻。\n\n这与分支污染不同。分支污染中，时间线本身会真正跳回过去。"),
        new(HelpTopic.Cleanup, "清理旧 偶像经理数据核心 数据", "清理是可选的。更安全的做法是先迁移、检查结果，再清理。\n\n• “成功后回收”只有在新 第6版 输出已经写入、重新打开并再次验证后才会执行。\n• “回收成功迁移项”只处理成功完成的源数据。\n• “回收孤立源”只适用于真正的“无普通存档匹配”项目。弱匹配和歧义匹配不会被当作孤立数据。\n• 文件会进入 微软视窗系统回收站，而不是永久删除。\n• 如果旧存档文件夹在 偶像经理数据核心 文件回收后变空，数据迁移工具 也会回收这个空文件夹。\n• 如果一个数据库包含多个存档流，在所有依赖它的存档流都能安全移除前，该数据库会保留。"),
        new(HelpTopic.Statuses, "常见批量计划状态", "就绪：普通迁移 — 旧数据和普通存档有可用匹配，计划也通过验证。\n\n就绪：分支保留 — 找到多条时间线，并且有一个分支可以较有把握地保留。\n\n就绪：干净基线 — 已知普通存档，但混合的旧历史无法安全分离。\n\n就绪：未来尾部截断 — 时间线连续，但超过了所选普通存档日期。\n\n弱普通存档匹配 — 找到候选，但自动证据不够强。请使用“解决匹配”。\n\n歧义普通存档匹配 — 两个或更多候选同样合适。请使用“解决匹配”。\n\n无普通存档匹配 — 没有识别到匹配的现有普通存档。旧存档可能已经删除或移动。\n\n旧源已被取代 — 更强的旧源已经指向同一个普通存档。\n\n验证失败 — 继续前请阅读“详细信息”。"),
        new(HelpTopic.Logs, "日志与故障排查", "大多数用户平时不需要诊断日志。窗口打不开、扫描报错，或者需要准确报告发生了什么时，可以使用“日志”。\n\n“打开目标位置”会打开当前 偶像经理数据核心 输出文件夹。迁移后想确认新 伴随数据文件 是否存在时很有用。\n\n如果某个警告看不懂，请先保留旧文件，不要强制清理，先检查对应行或单个迁移再继续。"),
    };
}
