<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ModName>IM Data Core</ModName>
    <RootNamespace>IMDataCore</RootNamespace>
    <AssemblyName>com.cosmo.imdatacore</AssemblyName>
    <Version>2.0.8</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\**\*.cs" />
  </ItemGroup>
</Project>
