<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ModName>IM UI Framework</ModName>
    <RootNamespace>IMUiFramework</RootNamespace>
    <AssemblyName>com.cosmo.imuiframework</AssemblyName>
    <Version>3.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\IMUiFramework.cs" />
    <Compile Include="src\IMUiCompat.cs" />
    <Compile Include="src\IMUiBridges.cs" />
    <Compile Include="src\IMUiTween.cs" />
    <Compile Include="src\VanillaUiResources.cs" />
    <Compile Include="src\VanillaUiTheme.cs" />
    <Compile Include="src\VanillaUiFonts.cs" />
    <Compile Include="src\VanillaUiSceneTemplates.cs" />
    <Compile Include="src\VanillaUiSceneCatalog.cs" />
    <Compile Include="src\VanillaUiSceneFactory.cs" />
    <Compile Include="src\VanillaPopupTemplateCatalog.cs" />
    <Compile Include="src\VanillaUiControlFactory.cs" />
    <Compile Include="src\VanillaUiPopupFactory.cs" />
    <Compile Include="src\VanillaUiReferenceTemplates.cs" />
    <Compile Include="src\IMUiPatterns.cs" />
    <Compile Include="src\IMUiPrimitives.cs" />
    <Compile Include="src\IMUiElementBuilder.cs" />
    <Compile Include="src\IMUiThemeV3.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DOTween" Private="false">
      <HintPath>$(dllDir)\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine" Private="false">
      <HintPath>$(dllDir)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreModule" Private="false">
      <HintPath>$(dllDir)\UnityEngine.TextCoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
