using Michsky.UI.ModernUIPack;
using TMPro;
using UnityEngine;

namespace GraduationCalendar.EmbeddedIMUiFramework
{
    /// <summary>
    /// Typed snapshot of every public MUIP Manager setting shipped with Idol Manager.
    /// Modify a copy and apply it per prefab without mutating the game's global MUIP Manager asset.
    /// </summary>
    public sealed class VanillaUiThemeSettings
    {
        public bool enableDynamicUpdate;
        public bool enableExtendedColorPicker;
        public bool editorHints;
        public Color animatedIconColor;
        public Color contextBackgroundColor;
        public UIManager.ButtonThemeType buttonThemeType;
        public TMP_FontAsset buttonFont;
        public float buttonFontSize;
        public Color buttonBorderColor;
        public Color buttonFilledColor;
        public Color buttonTextBasicColor;
        public Color buttonTextColor;
        public Color buttonTextHighlightedColor;
        public Color buttonIconBasicColor;
        public Color buttonIconColor;
        public Color buttonIconHighlightedColor;
        public TMP_FontAsset dropdownItemFont;
        public float dropdownItemFontSize;
        public UIManager.DropdownThemeType dropdownThemeType;
        public UIManager.DropdownAnimationType dropdownAnimationType;
        public TMP_FontAsset dropdownFont;
        public float dropdownFontSize;
        public Color dropdownColor;
        public Color dropdownTextColor;
        public Color dropdownIconColor;
        public Color dropdownItemColor;
        public Color dropdownItemTextColor;
        public Color dropdownItemIconColor;
        public TMP_FontAsset selectorFont;
        public float hSelectorFontSize;
        public Color selectorColor;
        public Color selectorHighlightedColor;
        public bool hSelectorInvertAnimation;
        public bool hSelectorLoopSelection;
        public TMP_FontAsset inputFieldFont;
        public float inputFieldFontSize;
        public Color inputFieldColor;
        public TMP_FontAsset modalWindowTitleFont;
        public TMP_FontAsset modalWindowContentFont;
        public UIManager.DropdownThemeType modalThemeType;
        public Color modalWindowTitleColor;
        public Color modalWindowDescriptionColor;
        public Color modalWindowIconColor;
        public Color modalWindowBackgroundColor;
        public Color modalWindowContentPanelColor;
        public TMP_FontAsset notificationTitleFont;
        public float notificationTitleFontSize;
        public TMP_FontAsset notificationDescriptionFont;
        public float notificationDescriptionFontSize;
        public UIManager.NotificationThemeType notificationThemeType;
        public Color notificationBackgroundColor;
        public Color notificationTitleColor;
        public Color notificationDescriptionColor;
        public Color notificationIconColor;
        public TMP_FontAsset progressBarLabelFont;
        public float progressBarLabelFontSize;
        public Color progressBarColor;
        public Color progressBarBackgroundColor;
        public Color progressBarLoopBackgroundColor;
        public Color progressBarLabelColor;
        public Color scrollbarColor;
        public Color scrollbarBackgroundColor;
        public TMP_FontAsset sliderLabelFont;
        public float sliderLabelFontSize;
        public UIManager.SliderThemeType sliderThemeType;
        public Color sliderColor;
        public Color sliderBackgroundColor;
        public Color sliderLabelColor;
        public Color sliderPopupLabelColor;
        public Color sliderHandleColor;
        public Color switchBorderColor;
        public Color switchBackgroundColor;
        public Color switchHandleOnColor;
        public Color switchHandleOffColor;
        public TMP_FontAsset toggleFont;
        public float toggleFontSize;
        public UIManager.ToggleThemeType toggleThemeType;
        public Color toggleTextColor;
        public Color toggleBorderColor;
        public Color toggleBackgroundColor;
        public Color toggleCheckColor;
        public TMP_FontAsset tooltipFont;
        public float tooltipFontSize;
        public Color tooltipTextColor;
        public Color tooltipBackgroundColor;

        public static VanillaUiThemeSettings FromVanilla()
        {
            return From(VanillaUiResources.GetMuipManager());
        }

        public static VanillaUiThemeSettings From(UIManager source)
        {
            if (source == null) return null;
            VanillaUiThemeSettings settings = new VanillaUiThemeSettings();
            settings.enableDynamicUpdate = source.enableDynamicUpdate;
            settings.enableExtendedColorPicker = source.enableExtendedColorPicker;
            settings.editorHints = source.editorHints;
            settings.animatedIconColor = source.animatedIconColor;
            settings.contextBackgroundColor = source.contextBackgroundColor;
            settings.buttonThemeType = source.buttonThemeType;
            settings.buttonFont = source.buttonFont;
            settings.buttonFontSize = source.buttonFontSize;
            settings.buttonBorderColor = source.buttonBorderColor;
            settings.buttonFilledColor = source.buttonFilledColor;
            settings.buttonTextBasicColor = source.buttonTextBasicColor;
            settings.buttonTextColor = source.buttonTextColor;
            settings.buttonTextHighlightedColor = source.buttonTextHighlightedColor;
            settings.buttonIconBasicColor = source.buttonIconBasicColor;
            settings.buttonIconColor = source.buttonIconColor;
            settings.buttonIconHighlightedColor = source.buttonIconHighlightedColor;
            settings.dropdownItemFont = source.dropdownItemFont;
            settings.dropdownItemFontSize = source.dropdownItemFontSize;
            settings.dropdownThemeType = source.dropdownThemeType;
            settings.dropdownAnimationType = source.dropdownAnimationType;
            settings.dropdownFont = source.dropdownFont;
            settings.dropdownFontSize = source.dropdownFontSize;
            settings.dropdownColor = source.dropdownColor;
            settings.dropdownTextColor = source.dropdownTextColor;
            settings.dropdownIconColor = source.dropdownIconColor;
            settings.dropdownItemColor = source.dropdownItemColor;
            settings.dropdownItemTextColor = source.dropdownItemTextColor;
            settings.dropdownItemIconColor = source.dropdownItemIconColor;
            settings.selectorFont = source.selectorFont;
            settings.hSelectorFontSize = source.hSelectorFontSize;
            settings.selectorColor = source.selectorColor;
            settings.selectorHighlightedColor = source.selectorHighlightedColor;
            settings.hSelectorInvertAnimation = source.hSelectorInvertAnimation;
            settings.hSelectorLoopSelection = source.hSelectorLoopSelection;
            settings.inputFieldFont = source.inputFieldFont;
            settings.inputFieldFontSize = source.inputFieldFontSize;
            settings.inputFieldColor = source.inputFieldColor;
            settings.modalWindowTitleFont = source.modalWindowTitleFont;
            settings.modalWindowContentFont = source.modalWindowContentFont;
            settings.modalThemeType = source.modalThemeType;
            settings.modalWindowTitleColor = source.modalWindowTitleColor;
            settings.modalWindowDescriptionColor = source.modalWindowDescriptionColor;
            settings.modalWindowIconColor = source.modalWindowIconColor;
            settings.modalWindowBackgroundColor = source.modalWindowBackgroundColor;
            settings.modalWindowContentPanelColor = source.modalWindowContentPanelColor;
            settings.notificationTitleFont = source.notificationTitleFont;
            settings.notificationTitleFontSize = source.notificationTitleFontSize;
            settings.notificationDescriptionFont = source.notificationDescriptionFont;
            settings.notificationDescriptionFontSize = source.notificationDescriptionFontSize;
            settings.notificationThemeType = source.notificationThemeType;
            settings.notificationBackgroundColor = source.notificationBackgroundColor;
            settings.notificationTitleColor = source.notificationTitleColor;
            settings.notificationDescriptionColor = source.notificationDescriptionColor;
            settings.notificationIconColor = source.notificationIconColor;
            settings.progressBarLabelFont = source.progressBarLabelFont;
            settings.progressBarLabelFontSize = source.progressBarLabelFontSize;
            settings.progressBarColor = source.progressBarColor;
            settings.progressBarBackgroundColor = source.progressBarBackgroundColor;
            settings.progressBarLoopBackgroundColor = source.progressBarLoopBackgroundColor;
            settings.progressBarLabelColor = source.progressBarLabelColor;
            settings.scrollbarColor = source.scrollbarColor;
            settings.scrollbarBackgroundColor = source.scrollbarBackgroundColor;
            settings.sliderLabelFont = source.sliderLabelFont;
            settings.sliderLabelFontSize = source.sliderLabelFontSize;
            settings.sliderThemeType = source.sliderThemeType;
            settings.sliderColor = source.sliderColor;
            settings.sliderBackgroundColor = source.sliderBackgroundColor;
            settings.sliderLabelColor = source.sliderLabelColor;
            settings.sliderPopupLabelColor = source.sliderPopupLabelColor;
            settings.sliderHandleColor = source.sliderHandleColor;
            settings.switchBorderColor = source.switchBorderColor;
            settings.switchBackgroundColor = source.switchBackgroundColor;
            settings.switchHandleOnColor = source.switchHandleOnColor;
            settings.switchHandleOffColor = source.switchHandleOffColor;
            settings.toggleFont = source.toggleFont;
            settings.toggleFontSize = source.toggleFontSize;
            settings.toggleThemeType = source.toggleThemeType;
            settings.toggleTextColor = source.toggleTextColor;
            settings.toggleBorderColor = source.toggleBorderColor;
            settings.toggleBackgroundColor = source.toggleBackgroundColor;
            settings.toggleCheckColor = source.toggleCheckColor;
            settings.tooltipFont = source.tooltipFont;
            settings.tooltipFontSize = source.tooltipFontSize;
            settings.tooltipTextColor = source.tooltipTextColor;
            settings.tooltipBackgroundColor = source.tooltipBackgroundColor;
            return settings;
        }

        public VanillaUiThemeSettings Clone()
        {
            VanillaUiThemeSettings settings = new VanillaUiThemeSettings();
            settings.enableDynamicUpdate = enableDynamicUpdate;
            settings.enableExtendedColorPicker = enableExtendedColorPicker;
            settings.editorHints = editorHints;
            settings.animatedIconColor = animatedIconColor;
            settings.contextBackgroundColor = contextBackgroundColor;
            settings.buttonThemeType = buttonThemeType;
            settings.buttonFont = buttonFont;
            settings.buttonFontSize = buttonFontSize;
            settings.buttonBorderColor = buttonBorderColor;
            settings.buttonFilledColor = buttonFilledColor;
            settings.buttonTextBasicColor = buttonTextBasicColor;
            settings.buttonTextColor = buttonTextColor;
            settings.buttonTextHighlightedColor = buttonTextHighlightedColor;
            settings.buttonIconBasicColor = buttonIconBasicColor;
            settings.buttonIconColor = buttonIconColor;
            settings.buttonIconHighlightedColor = buttonIconHighlightedColor;
            settings.dropdownItemFont = dropdownItemFont;
            settings.dropdownItemFontSize = dropdownItemFontSize;
            settings.dropdownThemeType = dropdownThemeType;
            settings.dropdownAnimationType = dropdownAnimationType;
            settings.dropdownFont = dropdownFont;
            settings.dropdownFontSize = dropdownFontSize;
            settings.dropdownColor = dropdownColor;
            settings.dropdownTextColor = dropdownTextColor;
            settings.dropdownIconColor = dropdownIconColor;
            settings.dropdownItemColor = dropdownItemColor;
            settings.dropdownItemTextColor = dropdownItemTextColor;
            settings.dropdownItemIconColor = dropdownItemIconColor;
            settings.selectorFont = selectorFont;
            settings.hSelectorFontSize = hSelectorFontSize;
            settings.selectorColor = selectorColor;
            settings.selectorHighlightedColor = selectorHighlightedColor;
            settings.hSelectorInvertAnimation = hSelectorInvertAnimation;
            settings.hSelectorLoopSelection = hSelectorLoopSelection;
            settings.inputFieldFont = inputFieldFont;
            settings.inputFieldFontSize = inputFieldFontSize;
            settings.inputFieldColor = inputFieldColor;
            settings.modalWindowTitleFont = modalWindowTitleFont;
            settings.modalWindowContentFont = modalWindowContentFont;
            settings.modalThemeType = modalThemeType;
            settings.modalWindowTitleColor = modalWindowTitleColor;
            settings.modalWindowDescriptionColor = modalWindowDescriptionColor;
            settings.modalWindowIconColor = modalWindowIconColor;
            settings.modalWindowBackgroundColor = modalWindowBackgroundColor;
            settings.modalWindowContentPanelColor = modalWindowContentPanelColor;
            settings.notificationTitleFont = notificationTitleFont;
            settings.notificationTitleFontSize = notificationTitleFontSize;
            settings.notificationDescriptionFont = notificationDescriptionFont;
            settings.notificationDescriptionFontSize = notificationDescriptionFontSize;
            settings.notificationThemeType = notificationThemeType;
            settings.notificationBackgroundColor = notificationBackgroundColor;
            settings.notificationTitleColor = notificationTitleColor;
            settings.notificationDescriptionColor = notificationDescriptionColor;
            settings.notificationIconColor = notificationIconColor;
            settings.progressBarLabelFont = progressBarLabelFont;
            settings.progressBarLabelFontSize = progressBarLabelFontSize;
            settings.progressBarColor = progressBarColor;
            settings.progressBarBackgroundColor = progressBarBackgroundColor;
            settings.progressBarLoopBackgroundColor = progressBarLoopBackgroundColor;
            settings.progressBarLabelColor = progressBarLabelColor;
            settings.scrollbarColor = scrollbarColor;
            settings.scrollbarBackgroundColor = scrollbarBackgroundColor;
            settings.sliderLabelFont = sliderLabelFont;
            settings.sliderLabelFontSize = sliderLabelFontSize;
            settings.sliderThemeType = sliderThemeType;
            settings.sliderColor = sliderColor;
            settings.sliderBackgroundColor = sliderBackgroundColor;
            settings.sliderLabelColor = sliderLabelColor;
            settings.sliderPopupLabelColor = sliderPopupLabelColor;
            settings.sliderHandleColor = sliderHandleColor;
            settings.switchBorderColor = switchBorderColor;
            settings.switchBackgroundColor = switchBackgroundColor;
            settings.switchHandleOnColor = switchHandleOnColor;
            settings.switchHandleOffColor = switchHandleOffColor;
            settings.toggleFont = toggleFont;
            settings.toggleFontSize = toggleFontSize;
            settings.toggleThemeType = toggleThemeType;
            settings.toggleTextColor = toggleTextColor;
            settings.toggleBorderColor = toggleBorderColor;
            settings.toggleBackgroundColor = toggleBackgroundColor;
            settings.toggleCheckColor = toggleCheckColor;
            settings.tooltipFont = tooltipFont;
            settings.tooltipFontSize = tooltipFontSize;
            settings.tooltipTextColor = tooltipTextColor;
            settings.tooltipBackgroundColor = tooltipBackgroundColor;
            return settings;
        }

        public void ApplyTo(UIManager target)
        {
            if (target == null) return;
            target.enableDynamicUpdate = enableDynamicUpdate;
            target.enableExtendedColorPicker = enableExtendedColorPicker;
            target.editorHints = editorHints;
            target.animatedIconColor = animatedIconColor;
            target.contextBackgroundColor = contextBackgroundColor;
            target.buttonThemeType = buttonThemeType;
            target.buttonFont = buttonFont;
            target.buttonFontSize = buttonFontSize;
            target.buttonBorderColor = buttonBorderColor;
            target.buttonFilledColor = buttonFilledColor;
            target.buttonTextBasicColor = buttonTextBasicColor;
            target.buttonTextColor = buttonTextColor;
            target.buttonTextHighlightedColor = buttonTextHighlightedColor;
            target.buttonIconBasicColor = buttonIconBasicColor;
            target.buttonIconColor = buttonIconColor;
            target.buttonIconHighlightedColor = buttonIconHighlightedColor;
            target.dropdownItemFont = dropdownItemFont;
            target.dropdownItemFontSize = dropdownItemFontSize;
            target.dropdownThemeType = dropdownThemeType;
            target.dropdownAnimationType = dropdownAnimationType;
            target.dropdownFont = dropdownFont;
            target.dropdownFontSize = dropdownFontSize;
            target.dropdownColor = dropdownColor;
            target.dropdownTextColor = dropdownTextColor;
            target.dropdownIconColor = dropdownIconColor;
            target.dropdownItemColor = dropdownItemColor;
            target.dropdownItemTextColor = dropdownItemTextColor;
            target.dropdownItemIconColor = dropdownItemIconColor;
            target.selectorFont = selectorFont;
            target.hSelectorFontSize = hSelectorFontSize;
            target.selectorColor = selectorColor;
            target.selectorHighlightedColor = selectorHighlightedColor;
            target.hSelectorInvertAnimation = hSelectorInvertAnimation;
            target.hSelectorLoopSelection = hSelectorLoopSelection;
            target.inputFieldFont = inputFieldFont;
            target.inputFieldFontSize = inputFieldFontSize;
            target.inputFieldColor = inputFieldColor;
            target.modalWindowTitleFont = modalWindowTitleFont;
            target.modalWindowContentFont = modalWindowContentFont;
            target.modalThemeType = modalThemeType;
            target.modalWindowTitleColor = modalWindowTitleColor;
            target.modalWindowDescriptionColor = modalWindowDescriptionColor;
            target.modalWindowIconColor = modalWindowIconColor;
            target.modalWindowBackgroundColor = modalWindowBackgroundColor;
            target.modalWindowContentPanelColor = modalWindowContentPanelColor;
            target.notificationTitleFont = notificationTitleFont;
            target.notificationTitleFontSize = notificationTitleFontSize;
            target.notificationDescriptionFont = notificationDescriptionFont;
            target.notificationDescriptionFontSize = notificationDescriptionFontSize;
            target.notificationThemeType = notificationThemeType;
            target.notificationBackgroundColor = notificationBackgroundColor;
            target.notificationTitleColor = notificationTitleColor;
            target.notificationDescriptionColor = notificationDescriptionColor;
            target.notificationIconColor = notificationIconColor;
            target.progressBarLabelFont = progressBarLabelFont;
            target.progressBarLabelFontSize = progressBarLabelFontSize;
            target.progressBarColor = progressBarColor;
            target.progressBarBackgroundColor = progressBarBackgroundColor;
            target.progressBarLoopBackgroundColor = progressBarLoopBackgroundColor;
            target.progressBarLabelColor = progressBarLabelColor;
            target.scrollbarColor = scrollbarColor;
            target.scrollbarBackgroundColor = scrollbarBackgroundColor;
            target.sliderLabelFont = sliderLabelFont;
            target.sliderLabelFontSize = sliderLabelFontSize;
            target.sliderThemeType = sliderThemeType;
            target.sliderColor = sliderColor;
            target.sliderBackgroundColor = sliderBackgroundColor;
            target.sliderLabelColor = sliderLabelColor;
            target.sliderPopupLabelColor = sliderPopupLabelColor;
            target.sliderHandleColor = sliderHandleColor;
            target.switchBorderColor = switchBorderColor;
            target.switchBackgroundColor = switchBackgroundColor;
            target.switchHandleOnColor = switchHandleOnColor;
            target.switchHandleOffColor = switchHandleOffColor;
            target.toggleFont = toggleFont;
            target.toggleFontSize = toggleFontSize;
            target.toggleThemeType = toggleThemeType;
            target.toggleTextColor = toggleTextColor;
            target.toggleBorderColor = toggleBorderColor;
            target.toggleBackgroundColor = toggleBackgroundColor;
            target.toggleCheckColor = toggleCheckColor;
            target.tooltipFont = tooltipFont;
            target.tooltipFontSize = tooltipFontSize;
            target.tooltipTextColor = tooltipTextColor;
            target.tooltipBackgroundColor = tooltipBackgroundColor;
        }

        public UIManager CreateRuntimeAsset()
        {
            UIManager target = VanillaUiResources.CloneMuipManager();
            if (target == null) return null;
            ApplyTo(target);
            return target;
        }
    }
}
