<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ModName>Cheats Mod</ModName>
    <RootNamespace>CheatsMod</RootNamespace>
    <AssemblyName>com.cosmo.cheatsmod</AssemblyName>
    <Version>1.8.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\CheatsMod.cs" />
    <Compile Include="src\CheatUi.cs" />
    <Compile Include="src\CheatNumericEditor.cs" />
    <Compile Include="src\CheatNameEditor.cs" />
    <Compile Include="src\UniqueIdolRecruitmentEditing.cs" />
    <Compile Include="src\EmbeddedIMUiFramework\*.cs" />
    <Compile Include="src\UniqueIdolRecruitmentPopup.cs" />
    <Compile Include="src\GraduationCheatPopup.cs" />
    <Compile Include="src\IdolTargetCheatPopup.cs" />
    <Compile Include="src\BullyingCheat.cs" />
    <Compile Include="src\CliqueDisplayUi.cs" />
    <Compile Include="src\RelationshipAndCliqueCheats.cs" />
    <Compile Include="src\RoomActivityCheats.cs" />
    <Compile Include="src\EroEventsCheatPopup.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DOTween" Private="false">
      <HintPath>$(dllDir)\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine" Private="false">
      <HintPath>$(dllDir)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreModule" Private="false">
      <HintPath>$(dllDir)\UnityEngine.TextCoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule" Private="false">
      <HintPath>$(dllDir)\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule" Private="false">
      <HintPath>$(dllDir)\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
