param(
    [string]$SourceRoot = "..\src",
    [string]$OutputFile = "..\docs\EVENT_CATALOG.md"
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceRootPath = (Resolve-Path (Join-Path $scriptDir $SourceRoot)).Path
$outputPath = Join-Path $scriptDir $OutputFile
$outputDir = Split-Path -Parent $outputPath

if (!(Test-Path $sourceRootPath))
{
    throw "Source root not found: $sourceRootPath"
}

if (!(Test-Path $outputDir))
{
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$sourceFiles = Get-ChildItem -Path $sourceRootPath -Recurse -Filter "*.cs" -File | Sort-Object FullName
if ($sourceFiles.Count -eq 0)
{
    throw "No C# source files found under: $sourceRootPath"
}

$sourceText = ($sourceFiles | ForEach-Object { Get-Content -Path $_.FullName -Raw }) -join "`n"

$eventRegex = [regex]'internal const string (EventType[A-Za-z0-9_]+)\s*=\s*"([^"]+)";'
$eventMatches = $eventRegex.Matches($sourceText)

$events = foreach ($match in $eventMatches)
{
    $constant = $match.Groups[1].Value
    $eventType = $match.Groups[2].Value
    $domain = if ($eventType.Contains("_")) { $eventType.Split("_")[0] } else { $eventType }

    [PSCustomObject]@{
        EventType = $eventType
        Constant = $constant
        Domain = $domain
    }
}

$events = $events |
    Sort-Object Domain, EventType, Constant -Unique

# These built-in capture constants are deliberately filtered by CoreEventRetention
# before public timeline queries. Keep them visible as internal/transient telemetry,
# but never advertise them in the queryable event-type table.
$transientEventConstants = @(
    "EventTypeStatusChanged",
    "EventTypeResearchPointsAccrued",
    "EventTypeIdolEarningsRecorded"
)

$queryableEvents = $events | Where-Object {
    $transientEventConstants -notcontains $_.Constant
}
$transientEvents = $events | Where-Object {
    $transientEventConstants -contains $_.Constant
}

$jsonFieldRegex = [regex]'internal const string (JsonField[A-Za-z0-9_]+)\s*=\s*"([^"]+)";'
$jsonFieldMatches = $jsonFieldRegex.Matches($sourceText)

$payloadFields = foreach ($match in $jsonFieldMatches)
{
    $constant = $match.Groups[1].Value
    $fieldKey = $match.Groups[2].Value
    $domain = if ($fieldKey.Contains("_")) { $fieldKey.Split("_")[0] } else { $fieldKey }

    [PSCustomObject]@{
        FieldKey = $fieldKey
        Constant = $constant
        Domain = $domain
    }
}

$payloadFields = $payloadFields |
    Sort-Object Domain, FieldKey, Constant -Unique

$eventDomains = ($queryableEvents | Group-Object Domain).Count
$payloadDomains = ($payloadFields | Group-Object Domain).Count

$lines = New-Object System.Collections.Generic.List[string]
$null = $lines.Add("# IM Data Core Event Catalog")
$null = $lines.Add("")
$null = $lines.Add("This file is the reference list of queryable built-in IM Data Core event types, explicitly non-queryable internal capture types, and payload field constants.")
$null = $lines.Add("")
$null = $lines.Add("How to use this file:")
$null = $lines.Add("")
$null = $lines.Add("- Use **Event Type** from the **Queryable Built-in Event Types** table when you filter or classify timeline rows.")
$null = $lines.Add('- Use **Domain** to group related events (for example `single`, `show`, `contract`).')
$null = $lines.Add("- Use **Field Constant** names when mapping payload JSON fields to strongly typed code.")
$null = $lines.Add("")
$null = $lines.Add("Status-stream semantics:")
$null = $lines.Add("")
$null = $lines.Add('- `single_status_changed`, `show_status_changed`, and `tour_status_changed` observe their corresponding setter methods; they are not exhaustive lifecycle journals.')
$null = $lines.Add('- Vanilla direct assignments for initial single release, initial show release, and tour completion are represented by `single_released`, `show_released`, and `tour_finished`.')
$null = $lines.Add("")
$null = $lines.Add("Who this is for:")
$null = $lines.Add("")
$null = $lines.Add('- Mod authors who consume `IMDataCoreApi.TryReadRecentEventsForIdol(...)` or `IMDataCoreApi.TryReadEventsForIdolPage(...)`')
$null = $lines.Add("- Tooling authors building analytics/exporters for IM Data Core data")
$null = $lines.Add("")
$null = $lines.Add("What this file is not:")
$null = $lines.Add("")
$null = $lines.Add("- It is not a beginner tutorial for first integration.")
$null = $lines.Add("- It does not describe gameplay design intent for each event.")
$null = $lines.Add("")
$null = $lines.Add("For beginner integration:")
$null = $lines.Add("")
$null = $lines.Add('- Read `docs/START_HERE.md` first.')
$null = $lines.Add('- Then use `docs/COOKBOOK.md` for implementation patterns.')
$null = $lines.Add("")
$null = $lines.Add("Generation note:")
$null = $lines.Add("")
$null = $lines.Add('- Auto-generated from constant declarations in `src/**/*.cs` by `scripts/Generate-EventCatalog.ps1`.')
$null = $lines.Add("- Do not edit this file manually; regenerate it after event constant changes.")
$null = $lines.Add("")
$null = $lines.Add("## Summary")
$null = $lines.Add("")
$null = $lines.Add("- Queryable built-in event types: $($queryableEvents.Count)")
$null = $lines.Add("- Queryable event domains: $eventDomains")
$null = $lines.Add("- Internal transient event constants: $($transientEvents.Count)")
$null = $lines.Add("- Payload JSON field constants: $($payloadFields.Count)")
$null = $lines.Add("- Payload field domains: $payloadDomains")
$null = $lines.Add("")
$null = $lines.Add("## Queryable Built-in Event Types")
$null = $lines.Add("")
$null = $lines.Add("| Event Type | Constant | Domain |")
$null = $lines.Add("| --- | --- | --- |")

foreach ($eventRow in $queryableEvents)
{
    $null = $lines.Add("| $($eventRow.EventType) | $($eventRow.Constant) | $($eventRow.Domain) |")
}

$null = $lines.Add("")
$null = $lines.Add("## Internal Transient Event Types (Not Queryable)")
$null = $lines.Add("")
$null = $lines.Add("These implementation-telemetry captures are filtered by `CoreEventRetention` before durable/public timeline reads. Do not use them as timeline filters.")
$null = $lines.Add("")
$null = $lines.Add("| Event Type | Constant | Domain |")
$null = $lines.Add("| --- | --- | --- |")
foreach ($eventRow in $transientEvents)
{
    $null = $lines.Add("| $($eventRow.EventType) | $($eventRow.Constant) | $($eventRow.Domain) |")
}

$null = $lines.Add("")
$null = $lines.Add("## Payload JSON Field Keys")
$null = $lines.Add("")
$null = $lines.Add("| Field Key | Constant | Domain |")
$null = $lines.Add("| --- | --- | --- |")

foreach ($payloadRow in $payloadFields)
{
    $null = $lines.Add("| $($payloadRow.FieldKey) | $($payloadRow.Constant) | $($payloadRow.Domain) |")
}

Set-Content -Path $outputPath -Value $lines -Encoding UTF8
Write-Host "Generated catalog: $outputPath"
Write-Host "Source files scanned: $($sourceFiles.Count)"
Write-Host "Queryable events: $($queryableEvents.Count) | Transient events: $($transientEvents.Count) | Payload field constants: $($payloadFields.Count)"
