param(
    [string]$SourceRoot = "..\src",
    [string]$OutputFile = "..\docs\EVENT_CATALOG.md"
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourceRootPath = (Resolve-Path (Join-Path $scriptDir $SourceRoot)).Path
$outputPath = Join-Path $scriptDir $OutputFile
$outputDir = Split-Path -Parent $outputPath

if (!(Test-Path $sourceRootPath))
{
    throw "Source root not found: $sourceRootPath"
}

if (!(Test-Path $outputDir))
{
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$sourceFiles = Get-ChildItem -Path $sourceRootPath -Recurse -Filter "*.cs" -File | Sort-Object FullName
if ($sourceFiles.Count -eq 0)
{
    throw "No C# source files found under: $sourceRootPath"
}

$sourceText = ($sourceFiles | ForEach-Object { Get-Content -Path $_.FullName -Raw }) -join "`n"

$eventRegex = [regex]'internal const string (EventType[A-Za-z0-9_]+)\s*=\s*"([^"]+)";'
$eventMatches = $eventRegex.Matches($sourceText)

$events = foreach ($match in $eventMatches)
{
    $constant = $match.Groups[1].Value
    $eventType = $match.Groups[2].Value
    $domain = if ($eventType.Contains("_")) { $eventType.Split("_")[0] } else { $eventType }

    [PSCustomObject]@{
        EventType = $eventType
        Constant = $constant
        Domain = $domain
    }
}

$events = $events |
    Sort-Object Domain, EventType, Constant -Unique

$jsonFieldRegex = [regex]'internal const string (JsonField[A-Za-z0-9_]+)\s*=\s*"([^"]+)";'
$jsonFieldMatches = $jsonFieldRegex.Matches($sourceText)

$payloadFields = foreach ($match in $jsonFieldMatches)
{
    $constant = $match.Groups[1].Value
    $fieldKey = $match.Groups[2].Value
    $domain = if ($fieldKey.Contains("_")) { $fieldKey.Split("_")[0] } else { $fieldKey }

    [PSCustomObject]@{
        FieldKey = $fieldKey
        Constant = $constant
        Domain = $domain
    }
}

$payloadFields = $payloadFields |
    Sort-Object Domain, FieldKey, Constant -Unique

$eventDomains = ($events | Group-Object Domain).Count
$payloadDomains = ($payloadFields | Group-Object Domain).Count

$lines = New-Object System.Collections.Generic.List[string]
$null = $lines.Add("# IM Data Core Event Catalog")
$null = $lines.Add("")
$null = $lines.Add("This file is the reference list of built-in IM Data Core event types and payload field constants.")
$null = $lines.Add("")
$null = $lines.Add("How to use this file:")
$null = $lines.Add("- Use **Event Type** when you filter or classify timeline rows.")
$null = $lines.Add('- Use **Domain** to group related events (for example `single`, `show`, `contract`).')
$null = $lines.Add("- Use **Field Constant** names when mapping payload JSON fields to strongly typed code.")
$null = $lines.Add("")
$null = $lines.Add("Who this is for:")
$null = $lines.Add('- Mod authors who consume `IMDataCoreApi.TryReadRecentEventsForIdol(...)`')
$null = $lines.Add("- Tooling authors building analytics/exporters for IM Data Core data")
$null = $lines.Add("")
$null = $lines.Add("What this file is not:")
$null = $lines.Add("- It is not a beginner tutorial for first integration.")
$null = $lines.Add("- It does not describe gameplay design intent for each event.")
$null = $lines.Add("")
$null = $lines.Add("For beginner integration:")
$null = $lines.Add('- Read `docs/START_HERE.md` first.')
$null = $lines.Add('- Then use `docs/COOKBOOK.md` for implementation patterns.')
$null = $lines.Add("")
$null = $lines.Add("Generation note:")
$null = $lines.Add('- Auto-generated from constant declarations in `src/**/*.cs` by `scripts/Generate-EventCatalog.ps1`.')
$null = $lines.Add("- Do not edit this file manually; regenerate it after event constant changes.")
$null = $lines.Add("")
$null = $lines.Add("## Summary")
$null = $lines.Add("- Event type constants: $($events.Count)")
$null = $lines.Add("- Event domains: $eventDomains")
$null = $lines.Add("- Payload JSON field constants: $($payloadFields.Count)")
$null = $lines.Add("- Payload field domains: $payloadDomains")
$null = $lines.Add("")
$null = $lines.Add("## Built-in Event Types")
$null = $lines.Add("")
$null = $lines.Add("| Event Type | Constant | Domain |")
$null = $lines.Add("| --- | --- | --- |")

foreach ($eventRow in $events)
{
    $null = $lines.Add("| $($eventRow.EventType) | $($eventRow.Constant) | $($eventRow.Domain) |")
}

$null = $lines.Add("")
$null = $lines.Add("## Payload JSON Field Keys")
$null = $lines.Add("")
$null = $lines.Add("| Field Key | Constant | Domain |")
$null = $lines.Add("| --- | --- | --- |")

foreach ($payloadRow in $payloadFields)
{
    $null = $lines.Add("| $($payloadRow.FieldKey) | $($payloadRow.Constant) | $($payloadRow.Domain) |")
}

Set-Content -Path $outputPath -Value $lines -Encoding UTF8
Write-Host "Generated catalog: $outputPath"
Write-Host "Source files scanned: $($sourceFiles.Count)"
Write-Host "Event constants: $($events.Count) | Payload field constants: $($payloadFields.Count)"
