using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace StaffPortraits
{
    // The picker borrows the same tooltip manager as the senbatsu portraits, using its
    // staff overload so the card contains staff skills and assignment rather than idol stats.
    internal sealed class StaffPortraitPickerEntry : MonoBehaviour, IPointerEnterHandler,
        IPointerExitHandler, IPointerClickHandler
    {
        private const float HoverDelaySeconds = 0.35f;
        private staff._staff staffer;
        private staff staffManager;
        private TooltipManager tooltipManager;
        private Image portrait;
        private RectTransform viewport;
        private RectTransform entryRect;
        private Camera eventCamera;
        private bool hovering;
        private bool subscribed;
        private float hoverStartedAt;

        internal void Bind(staff._staff value, Image image, RectTransform clippingViewport)
        {
            Unsubscribe();
            staffer = value;
            portrait = image;
            viewport = clippingViewport;
            entryRect = GetComponent<RectTransform>();
            mainScript main = Camera.main == null ? null : Camera.main.GetComponent<mainScript>();
            if (main != null && main.Data != null)
            {
                staffManager = main.Data.GetComponent<staff>();
                tooltipManager = main.Data.GetComponent<TooltipManager>();
            }
            Subscribe();
            RefreshPortrait();
        }

        private void Subscribe()
        {
            if (subscribed || staffer == null) return;
            staffer.UpdatePortrait += RefreshPortrait;
            subscribed = true;
        }

        private void Unsubscribe()
        {
            if (subscribed && staffer != null) staffer.UpdatePortrait -= RefreshPortrait;
            subscribed = false;
        }

        private void RefreshPortrait()
        {
            if (portrait == null || staffer == null) return;
            portrait.sprite = null;
            portrait.color = Color.clear;
            if (staffer.texture == null && staffManager != null)
                staffManager.LoadPortrait_Small(staffer, portrait);
            // Composite textures are generated by the game's queue. Observe the finished
            // sprite below without starting a coroutine that could outlive this entry.
        }

        public void OnPointerEnter(PointerEventData eventData)
        {
            hovering = true;
            eventCamera = eventData.enterEventCamera;
            hoverStartedAt = Time.unscaledTime;
        }

        public void OnPointerExit(PointerEventData eventData) { hovering = false; }
        public void OnPointerClick(PointerEventData eventData) { hovering = false; }

        private void OnEnable()
        {
            Subscribe();
            RefreshPortrait();
        }

        private void OnDisable()
        {
            hovering = false;
            Unsubscribe();
            // TooltipManager hides its card in LateUpdate when no owner refreshes it.
        }

        private void Update()
        {
            if (staffer == null || portrait == null) return;
            if (staffer.texture != null && staffer.texture.small != null)
                portrait.sprite = staffer.texture.small;
            portrait.color = portrait.sprite == null ? Color.clear : Color.white;

            if (!hovering || tooltipManager == null) return;
            // Scrolling can move an entry beneath the pointer without a PointerExit.
            // Also check the viewport so clipped entries cannot leave a card on screen.
            if (!RectTransformUtility.RectangleContainsScreenPoint(entryRect, Input.mousePosition, eventCamera)
                || !RectTransformUtility.RectangleContainsScreenPoint(viewport, Input.mousePosition, eventCamera))
            {
                hovering = false;
                return;
            }
            if (Time.unscaledTime - hoverStartedAt >= HoverDelaySeconds)
                tooltipManager.ShowStatusButtonTooltip(gameObject, staffer, false);
        }
    }
}
